### ISSUE TITLE
Add support for exits numbering in roundabouts

### ISSUE THREAD

**Issue by TimMcCauley** [GIScience/openrouteservice-app#1]
_From @Rungee on September 19, 2016 7:45_

_Copied from original issue: GIScience/openrouteservice#351_

**Comment by TimMcCauley** [comment]
@rabidllama are we planning to support this in the backend with the next graphhopper update?

**Comment by TimMcCauley** [comment]
Let's support this in the new client.

**Comment by marq24** [comment]
... in the turn instructions we have already have the info to leave the rb at the n-exit - just as clarification - you you plan to have something like "leave at exit 2 of 6" ?! - so adding the total number of possible exits?

**Comment by TimMcCauley** [comment]
Oh, then it was added and this is a very old artefact from the... let me see ... 26th Oct *2016* 🥇
