### ISSUE TITLE
Add isochrones based on energy (kWh) for Electric Vehicles (Car, bikes, bus, trucks)

### ISSUE THREAD

**Issue by guiguid** [GIScience/openrouteservice-app#104]
Hi, 
thanks for this amazing tools.
Could you add feature for electrical vehicles ?

Like Electrical Car profile
Compute range on isochrones based on energy (accelerate, speed, brakes, climb, fall ...) in kWh

So your tool can answer to : 
Where can I go with an electric car and 40kWh of energy ?
Where can I go with an electric bike and 2kWh of energy ?
What is the more energy efficient way to go from here to XXX ?

thanks

**Comment by TimMcCauley** [comment]
@guiguid thank you for this, we would need some detailed expert knowledge to deal with this feature. Any idea who we could work with?

**Comment by Stemby** [comment]
#116 might be a requirement.

**Comment by TimMcCauley** [comment]
Closing this issue for now
