### ISSUE TITLE
The path is blocked by barrier nodes with access=yes 

### ISSUE THREAD

**Issue by BAKFR** [GIScience/openrouteservice-app#106]
Here:
https://openrouteservice.org/directions?a=48.617392,-2.027214,48.616804,-2.029284&b=0&c=0&k2=km

In this example, the proposed path is obviously wrong. The route is blocked by lift gates (tag `barrier=lift_gate` with `access=yes`). I think all barriers with `access=yes` should be accessible with the same permission as the route it belongs.

**Comment by TimMcCauley** [comment]
Thank you for the hint - issues is moved to our backend repository, will be fixed there.
