### ISSUE TITLE
Export doesn't work

### ISSUE THREAD

**Issue by Stemby** [GIScience/openrouteservice-app#115]
Hi,
I get a blank popup. See this screenshot:

![screenshot](https://user-images.githubusercontent.com/146789/27790279-1bb30818-5ff0-11e7-9be1-409111bb1039.png)

Same behavior with both Firefox and Chromium; OS: Debian testing.

Best regards,
Carlo

**Comment by TimMcCauley** [comment]
@Stemby could you clear your cache? Same behaviour then also?

**Comment by Stemby** [comment]
Yes. Same behavior also with both Firefox and Chromium for Android (6.0), with private browsing too.

**Comment by Rungee** [comment]
I have a feeling that this issue is somehow related to localization problem.
As it can be seen from a screenshot, "Additional information" is translated as "EXTRAS".  I was not able to find an UI language that contains such translation. Instead, "EXTRAS" is the name of a variable used in translations.

**Comment by TimMcCauley** [comment]
@Stemby could you please try now again? Please dont forget to refresh.

**Comment by Stemby** [comment]
@TimMcCauley 
Now it works on Debian, thanks!

Still the same problem on Android.

**Comment by Brianetta** [comment]
Just came here to open this issue, to find it already open. No luck here on Chrome or Firefox in Ubuntu 16.04 or Android 7.0. Occasionally I see `ors-export-linestring` in the filename field, and some valid options in the type selector, but more often both of these are blank, as in @Stemby's screenshot.

At no time have I been prompted by any browser to save a file. The submit button indicates that it has been clicked by changing shade, but there's nothing else. The issue is present at the time of posting. I've tried clearing my cache, and also using another machine and browser with another user logged in entirely (using the share link feature and email to pass the route over).

**Comment by TimMcCauley** [comment]
@Brianetta - thank you for the information. I refactored the corresponding code, could you please give it a new try? 724e167

**Comment by Brianetta** [comment]
This didn't help. I cleared all cached data in my browsers before giving it a try.

It seems that the download dialogue is affected by expanding the details.

After creating a route, this is what I see when I click the Export Route icon:
![image](https://user-images.githubusercontent.com/719817/27824528-b6f906d8-60a4-11e7-9f64-0f625c6c78ee.png)

If I next expand the details (in red here):
![image](https://user-images.githubusercontent.com/719817/27824576-d4e2dee4-60a4-11e7-8035-b6d6abec85de.png)

then subsequent requests to use Export Route give the following:
![image](https://user-images.githubusercontent.com/719817/27824504-a16b6f40-60a4-11e7-8dce-db26e16f41db.png)

This still doesn't respond to the Download button being clicked.

**Comment by TimMcCauley** [comment]
@Brianetta thank you. Now this is getting spooky, I have tried this on Ubuntu 16.04 myself just then on a fresh system with Firefox and it works. Which locale are you using of the Browser? Could you try this [add-on](https://stackoverflow.com/questions/1206042/how-to-get-firefox-language-setting-really) and set it to en-US? Does it make any difference?

**Comment by Brianetta** [comment]
In Chrome, I have en-gb, en-us and de-de (in that order). In Firefox, I have only en-GB installed. I'm not only getting this issue on my desktop browsers; I'm also getting it on Chrome on Android 7, where the locale is set globally as "English (United Kingdom)".

Chrome 59.0.3071.125 on Android 7.1.2 (I'm seeing similar on my Android 7.0 devices):
![screenshot_20170704-121546](https://user-images.githubusercontent.com/719817/27828151-a4d4d08c-60b2-11e7-8703-622b3e95c054.png)

**Comment by TimMcCauley** [comment]
@Brianetta also, could you paste your console.log output here? There should be some errors raised. Thanks for your support!

**Comment by Brianetta** [comment]
Got an error from the log in Chrome:

```
Object
vendor.90fc554bf3c2b847.js:24 TypeError: Cannot read property 'createElementNS' of undefined
    at vendor.90fc554bf3c2b847.js:62
    at Object.module.exports (vendor.90fc554bf3c2b847.js:62)
    at __webpack_require__ (vendor.90fc554bf3c2b847.js:62)
    at Object.SaveAs (vendor.90fc554bf3c2b847.js:62)
    at Object.invoke (vendor.90fc554bf3c2b847.js:21)
    at Object.enforcedReturnValue [as $get] (vendor.90fc554bf3c2b847.js:21)
    at Object.invoke (vendor.90fc554bf3c2b847.js:21)
    at vendor.90fc554bf3c2b847.js:21
    at getService (vendor.90fc554bf3c2b847.js:21)
    at injectionArgs (vendor.90fc554bf3c2b847.js:21)
(anonymous) @ vendor.90fc554bf3c2b847.js:24
(anonymous) @ vendor.90fc554bf3c2b847.js:23
processQueue @ vendor.90fc554bf3c2b847.js:25
(anonymous) @ vendor.90fc554bf3c2b847.js:25
$eval @ vendor.90fc554bf3c2b847.js:26
$digest @ vendor.90fc554bf3c2b847.js:26
$apply @ vendor.90fc554bf3c2b847.js:26
(anonymous) @ vendor.90fc554bf3c2b847.js:28
dispatch @ vendor.90fc554bf3c2b847.js:7
elemData.handle @ vendor.90fc554bf3c2b847.js:7
```

**Comment by TimMcCauley** [comment]
Thank you, on which action is this raised?

**Comment by Brianetta** [comment]
Clicking the export icon -> ![image](https://user-images.githubusercontent.com/719817/27828493-617d51c2-60b4-11e7-8eed-84e03a6f1f90.png)

**Comment by TimMcCauley** [comment]
Please try now again @Brianetta @Stemby

**Comment by Stemby** [comment]
Just tried with Firefox for Android: it works for me!

Thank you!

**Comment by Brianetta** [comment]
Also confirmed, I have exported a .gpx file.

**Comment by TimMcCauley** [comment]
Thank you, marking as resolved.
