### ISSUE TITLE
Elevation profile

### ISSUE THREAD

**Issue by Stemby** [GIScience/openrouteservice-app#116]
Hi,  
I'd find very useful the calculation (and rendering) of the elevation profile of a route.

Best regards,
Carlo

**Comment by TimMcCauley** [comment]
I added this functionality, https://github.com/GIScience/Leaflet.Heightgraph/commit/5f655699a877ef1946d03bb19ff2c3b0b3f8a3ac - also now live on www.openrouteservice.org

**Comment by Sandmania** [comment]
Could you elaborate how / when / where this should work? I see the profile tool, but no elevation data. It seems that the elevation array only contains a bunch of zeros.

[Route example](https://openrouteservice.org/directions?n1=69.150909&n2=21.116522&n3=9&a=69.011771,20.890844,69.286325,21.268167&b=2b&c=0&g1=-1&g2=0&k1=en-US&k2=km)

**Comment by TimMcCauley** [comment]
@Sandmania the elevation data currently only works for below 60 deg N. We are considering merging different data sets for the rest of the world but stay tuned for this. 

http://glcf.umd.edu/data/glsdem/description.shtml

**Comment by Sandmania** [comment]
@TimMcCauley any news on the elevation data above 60 deg N?

**Comment by TimMcCauley** [comment]
@Sandmania we are currently working on detaching our graphhopper-ors fork from openrouteservice that we can easily update to a newer graphhopper version which considers multi elevation providers! Could you please add an issue to the openrouteservice backend repository?
