### ISSUE TITLE
Can not find obviously simple route

### ISSUE THREAD

**Issue by gorn** [GIScience/openrouteservice-app#121]
Something very basic must be broken, since this [link](https://labs.openrouteservice.org/directions?n1=50.095325&n2=14.36265&n3=16&a=50.096977,14.354625,50.098133,14.361641&b=0&c=0&k1=en-US&k2=km)

returns 

> Error Code 299: Unable to find a route between points 1 (14.3546250 50.0969770) and 2 (14.3616410 50.0981330) 

for me

**Comment by TimMcCauley** [comment]
labs.openrouteservice.org features germany only, please use openrouteservice.org for global routing, this will work 

https://openrouteservice.org/directions?n1=50.091994&n2=14.371276&n3=15&a=50.096977,14.354625,50.098133,14.361641&b=0&c=0&k1=en-US&k2=km
