### ISSUE TITLE
Isochrone gives parameter 'range=3600' is out of range error with large (>60min) time values

### ISSUE THREAD

**Issue by Sandmania** [GIScience/openrouteservice-app#126]
Steps to reproduce:

1. Goto openrouteservice.org
2. Click isochrones button in left menu bar
3. Choose pedestrian -> hiking
4. Search for: Heidelberg
5. Choose first search result Heidelberg, Heidelberg, Baden-Württemberg
6. Open isochrone options
7. Drag time slider to 240min, observe interval to automatically change to 24 min
8. Click generate isochones
Url from browser: https://openrouteservice.org/reach?n1=49.412388&n2=8.681246&n3=18&a=49.412388,8.681247&b=2b&i=0&j1=240&j2=24&g1=-1&g2=0&k1=en-US&k2=km

Expected results:
Isochrones are drawn to map

Actual result:
The following error appears in bottom left corner:
Error
Code 304: Parameter 'range=3600' is out of range. Maximum possible value is 14400.0

In network logs, HTTP 400 is returned from the following call
https://api.openrouteservice.org/pisochrones?api_key=58d904a497c67e00015b45fcb45ea7b5993e4bcb5f8fda643ea796f4&attributes=area%7Creachfactor&format=json&interval=1440&location_type=start&locations=8.681247,49.412388&profile=foot-hiking&range=14400&range_type=time

Other observations: Basically any value over 60 minutes seems to result in this error.

**Comment by Rungee** [comment]
Thank you for reporting this bug. This issue will be fixed in the next release.

At the moment, you can generate isochrones for larger regions using distance mode which is limited to 100 km.

**Comment by Rungee** [comment]
The issue will be automatically resolved at openrouteservice.org once we update the graphs  (approx. middle of September). 

Closing this issue.
