### ISSUE TITLE
Ascent, descent, and elevation not consistent when planning different routes between same start and end

### ISSUE THREAD

**Issue by bevoorrading** [GIScience/openrouteservice-app#128]
When making a route between two points, the elevation difference often does not remain the same when adding a via point.

Steps to reproduce:
1. Go to openrouteservice.org
2. Select start and end point for route
3. Look at nett ascent, i.e., Ascent - Descent
4. If for pedestrian, look at elevation of end point
5. Add a via point somewhere
6. Look at nett ascent of new route. This often turns out to be different from the one in 3.
7. If for pedestrian, look at elevation of end point. Also often different from the one in 4.

Examples:
**For pedestrian**
[Simple A-B route](https://openrouteservice.org/directions?n1=51.502265&n2=10.001614&n3=15&a=51.500338,9.992929,51.504589,10.010369&b=2&c=0&g1=-1&g2=0&k1=en-US&k2=km)
[With a via point](https://openrouteservice.org/directions?n1=51.504489&n2=10.005144&n3=16&a=51.500338,9.992929,51.508248,9.998868,51.504589,10.010369&b=2&c=0&g1=-1&g2=0&k1=en-US&k2=km)
In the first case the nett ascent is 75m-79m = **-4m**, and in the second it is 72m-59m = **13m**.
The elevation of the end point is in the first case **294.5m**, and in the second it is **303.8m**.

**For car**
[Simple A-B route](https://openrouteservice.org/directions?n1=51.422306&n2=9.958806&n3=14&a=51.420834,9.928722,51.438494,9.961939&b=0&c=0&k1=en-US&k2=km)
[With via point](https://openrouteservice.org/directions?n1=51.444111&n2=9.973097&n3=13&a=51.420834,9.928722,51.416499,9.969578,51.438494,9.961939&b=0&c=0&k1=en-US&k2=km)
In the first case the nett ascent is **62m**, and in the second case it is 148m-92m = **56m**.

**Comment by TimMcCauley** [comment]
thanks for sharing @bevoorrading we are investigating!

**Comment by TimMcCauley** [comment]
The reason for this mismatch is the quite low resolution of SRTM data. The result origins from smoothing and snapping the data. Nothing we can do at this point. Considering this issue as resolved.
