### ISSUE TITLE
avoid_features incorrect value

### ISSUE THREAD

**Issue by petrot** [GIScience/openrouteservice-app#130]
I got the following error: Parameter 'avoid_features' has incorrect value of 'tollways'.

This filter fails on the demo page, too: https://openrouteservice.org/directions?n1=47.465613&n2=18.94176&n3=14&b=0&k1=hu&k2=km

**Comment by TimMcCauley** [comment]
Greetings @petrot this issue will be solved within the next 4 weeks, we are aware it exists. I will keep this issue open and let you know when the API is updated!

**Comment by petrot** [comment]
Thanks!

**Comment by petrot** [comment]
@TimMcCauley this commit solved the problem? https://github.com/GIScience/openrouteservice/commit/076a55637f526ba7bc2cc71e27f26edf87739de7

**Comment by Rungee** [comment]
@petrot no, it doesn't. The issue needs to be resolved on the server side. We are planning to make an update within 2-3 weeks.

**Comment by petrot** [comment]
ok, thanks for the info!

**Comment by Rungee** [comment]
Hi @petrot.
We have finally updated ORS backend. Could you please check if the issue still persists?

**Comment by petrot** [comment]
Hi @Rungee!

It works fine, thank you!! :)
