### ISSUE TITLE
On the MapSurfer Map are Parking icons missing

### ISSUE THREAD

**Issue by Mannshoch** [GIScience/openrouteservice-app#134]
See following position and compare it with OpenStreetMap:

https://www.openrouteservice.org/directions?n1=47.388515&n2=8.488154&n3=18&a=null,null,47.389441,8.48762&b=0&c=0&k1=de&k2=km

**Comment by TimMcCauley** [comment]
Greetings @Mannshoch MapSurfer Maps havent been updated for a couple of months. We will update them soon, you will then be able to see the icons.
