### ISSUE TITLE
Avoid road types track & route preference weight=shortest does not exclude track

### ISSUE THREAD

**Issue by defaste** [GIScience/openrouteservice-app#135]
Steps to reproduce:
From: 220 Hrušica, Hrušica 220, Jesenice, Jesenice
To: 42 Grajska cesta, Grajska cesta 42, Bled
Route preference weight: **shortest**
Avoid road types: **tracks** (unpaved roads both selected or unselected does not change the result)

Changing route preference weight gives me a correct solution.

Hope this help.

Edit: Avoid road types: highways works as expected (same example)

**Comment by Rungee** [comment]
defaste,
Thanks for your feedback. The issue has been already fixed in the backend. It will be automatically resolved at openrouteservice.org once we update the graphs  (approx. middle of September).
