### ISSUE TITLE
City/address resolved incorrectly

### ISSUE THREAD

**Issue by frafra** [GIScience/openrouteservice-app#137]
https://openrouteservice.org/directions?n1=43.788779&n2=7.635807&n3=18&a=43.789173,7.635112,43.788465,7.636324&b=0&c=0&k1=en-US&k2=km

In this case the first location should be named "Via Piazza d'armi, Camporosso, Imperia", while the second one should be "Via San Vincenzo, Vallecrosia, Imperia" (Bordighera is a different city, located 2 Km eastwards compared to Camporosso e Vallecrosia)

openstreetmap resolves the address correctly in this case:
https://www.openstreetmap.org/search?query=43.789173%2C7.635112
https://www.openstreetmap.org/search?query=43.788779%2C7.635807

**Comment by pkubowicz** [comment]
An another case: type "focha 32, kraków" in the search field
- openrouteservice.org - only matches the city
- openstreetmap.org - matches the correct building

**Comment by TimMcCauley** [comment]
@pkubowicz your issue will be resolved in the next update.
@frafra this is a data issue, which currently can't be resolved due to [who's on first](https://github.com/whosonfirst-data/). 

Closing this issue for now.

**Comment by nilsnolde** [comment]
These are generally data issues for the underlying Pelias geocoder instance. This repo is not concerned with data issues.

Please use https://ask.openrouteservice.org for geocoding issues.
