### ISSUE TITLE
option to save routes to specific folder

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice-app#143]
make download folder customizable

**Comment by TheGreatRefrigerator** [comment]
is not possible for security reasons:
https://stackoverflow.com/questions/9840923/get-browser-download-path-with-javascript/9840961#9840961

**Comment by TimMcCauley** [comment]
I think it is possible but by default Chrome, FF etc just save to downloads without asking where to save to:

Found this: I believe it is a per-browser feature. In chrome, you set it in settings, advanced settings, checkbox "Ask where to save each file before downloading

**Comment by TimMcCauley** [comment]
https://stackoverflow.com/questions/11336663/how-to-make-a-browser-display-a-save-as-dialog-so-the-user-can-save-the-conten

**Comment by TheGreatRefrigerator** [comment]
https://stackoverflow.com/questions/11336663/how-to-make-a-browser-display-a-save-as-dialog-so-the-user-can-save-the-conten

**Comment by TheGreatRefrigerator** [comment]
@TimMcCauley  but that setting can't be changed by us with javascript..
The user has to change it himself i think.
We could drop a hint like: if you want to save to specific folder, change browser setting

**Comment by TimMcCauley** [comment]
Yes, you are right. Just wanted to clarify, consider this issue as closed.
