### ISSUE TITLE
Option to choose which map to use for routing

### ISSUE THREAD

**Issue by bevoorrading** [GIScience/openrouteservice-app#144]
First, let me tell you I really enjoy openrouteservice and really appreciate your work.

It seems like openrouteservice always uses the MapSurfer layer to calculate a route, regardless of which layer is chosen by the user. Would it be possible to have the option for the user to choose which maps to use for the routing? Because the different layers do not always have all the same tracks.

**Comment by TimMcCauley** [comment]
Greetings,

let me briefly explain how ORS works. The maps you see are merely used for visualization. The routes are calculated on the server which may currently use an older dataset than the maps of the frontend. As an example: the Openstreetmap tiles will be up to date with the current state of OSM whereas our server (until we update it) uses an OSM dataset which is about 2 months old. 

We are currently working on a faster update process cycle of our servers to provide you with a more  up to date OSM dataset.

Stay tuned - considering this now as closed.
