### ISSUE TITLE
Open Space Routing not working on labs instance

### ISSUE THREAD

**Issue by nrenner** [GIScience/openrouteservice-app#145]
[Open Space Routing](http://k1z.blog.uni-heidelberg.de/2017/06/24/introducing-labsopenrouteserviceorg-with-open-space-routing-and-the-places-poi-search-api/) on LABS.OpenRouteService.org seems not work, e.g.

https://labs.openrouteservice.org/directions?n1=49.410198&n2=8.707263&n3=18&a=49.410879,8.706424,49.409689,8.707899&b=2&c=0&g1=-1&g2=0&k1=en-US&k2=km

**Comment by TimMcCauley** [comment]
Will be fixed soonish

**Comment by nrenner** [comment]
Still doesn't seem to work, despite [recent post](http://k1z.blog.uni-heidelberg.de/2017/11/27/routing-through-open-spaces-%e2%80%93-a-performance-comparison-of-algorithms/) on the topic saying so?
