### ISSUE TITLE
Unable to compute some itineraries

### ISSUE THREAD

**Issue by Phyks** [GIScience/openrouteservice-app#156]
Hi,

Thanks for this great routing app on top of OSM data, it's one of the best one I've found so far!

I noticed that in some areas the itineraries I get are not really the ones expected. Here is a minimal itinerary to reproduce: https://openrouteservice.org/directions?n1=37.919691&n2=-119.209728&n3=12&a=37.926874,-119.022564,37.949342,-119.195824,37.919284,-119.255562&b=0&c=0&k1=en-US&k2=km.

OpenRouteService computes an itinerary passing north and doing many extra miles when it should be able to just take CA-120 directly (at least, I've done it myself a couple of weeks ago, there is a toll, but that's not a restricted route :).

Not sure what happens and if it is coming from OSM data (although they look fine on the map) or from OpenRouteService.

Let me know if I can help debugging in any ways,
Thanks!

P.S.: Same thing was happening yesterday with this itinerary: https://openrouteservice.org/directions?n1=41.837339&n2=-70.401077&n3=10&a=41.974796,-70.973359,42.06289,-70.201392,41.922194,-70.002008&b=0&c=0&k1=en-US&k2=km. But it seems there is no longer an issue for this one today.

**Comment by TimMcCauley** [comment]
@Phyks I just checked on openstreetmap.org and found this:

http://www.openstreetmap.org/node/2727957232#map=18/37.93084/-119.16623

```tioga pass road: corrected seasonal opening condition
access:conditional | no @ Nov-May
```

I guess this is the reason? Considering this issue as closed for now. If this condition is not correct feel free to change it on openstreetmap.org and we will consider it automatically in the next update.

**Comment by Phyks** [comment]
> access:conditional | no @ Nov-May

That's totally true and relevant, indeed. This road is closed in winter.

I did not know `OpenRouteService` could you such information, that's awesome!

However, if it can use this, there should be a UI counterpart. I don't know much about the tech stack behind the webapp, so my proposals might not be doable :/ I would propose to have:
* A different rendering of routes when they are closed (typically, having some visual hint on the Tioga pass road would have made me realize there was some seasonal closing). In this particular case, I knew the road and could have realized what was happening, but this might lead a new user planning a road trip to think the software is buggy.
* A way to select a "date of travel" so that we can still get the correct route to show it.

My initial goal was to share my last road trip itinerary, but this would require to be able to link to a stable itinerary which matches the one I made. :)

Thanks!

**Comment by TimMcCauley** [comment]
@Phyks this UI counterpart would be a great feature. We however currently do not have the resources to implement this. I'll keep it in mind though 👍  thanks!
