### ISSUE TITLE
Add Border Restriction Options

### ISSUE THREAD

**Issue by rabidllama** [GIScience/openrouteservice-app#157]
Add client functionality to avoid borders either from an option to avoid borders (all borders or controlled borders) or as a selection from a list of individual countries to avoid.

**Comment by TimMcCauley** [comment]
Let us use a searchable list for the 15x countries of the globe, each country has a checkbox which can be selected by the user, an example http://plnkr.co/edit/scuPYt?p=preview @rabidllama @TheGreatRefrigerator  what do you think?
