### ISSUE TITLE
System Error not fading after new route computation

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice-app#161]
The Error windows in the bottom left corner are not removed automatically, when a new route is computed.
Error pops up when address is not found or server not reachable.

**Comment by TimMcCauley** [comment]
@TheGreatRefrigerator they are currently just being replaced. You could add the [fade animation to it after n amount of seconds](http://plnkr.co/edit/HWi0FfDOsHeSOkcrRtN2?p=preview)
