### ISSUE TITLE
Automatically add semver version to information

### ISSUE THREAD

**Issue by TimMcCauley** [GIScience/openrouteservice-app#166]

**Comment by TheGreatRefrigerator** [comment]
Use grunt task to add and modify html to the info popup

**Comment by TheGreatRefrigerator** [comment]
Closed using [grunt-version](https://www.npmjs.com/package/grunt-version) in https://gitlab.gistools.geog.uni-heidelberg.de/giscience/openrouteservice-infrastructure/ors-client-files/commit/54bd3b0b6a431d6efc78b8574e946fad682754f2
