### ISSUE TITLE
the slope of the routes are shown fals

### ISSUE THREAD

**Issue by davidribbon** [GIScience/openrouteservice-app#175]
![grafik](https://user-images.githubusercontent.com/32144160/34761827-ae46a85c-f5e5-11e7-9abe-0daae213049e.png)

The slope of a way can either be positive or negative according the direction of travel. The patterns provided on the route details should take that into account and use "minus" slopes as well to provide a better insight. this is most valuable for especially truck drivers.

**Comment by TimMcCauley** [comment]
@davidribbon we use the colors to depict negative vs. positive - does this not suffice?
