### ISSUE TITLE
Error Code 2099 references always point 1

### ISSUE THREAD

**Issue by pathmapper** [GIScience/openrouteservice-app#194]
If a point can't be used for the routing, the Error Code 2099 references always point 1, regardless which point is causing the error (the coordinates shown in the error message are correct).

Example:

![auswahl_103](https://user-images.githubusercontent.com/20856381/36799234-f35bda1e-1cac-11e8-8258-77f6c1b1608c.png)

**Comment by pathmapper** [comment]
@TimMcCauley the issue is still there:

![Bildschirmfoto von »2019-07-13 09-52-11«](https://user-images.githubusercontent.com/20856381/61168825-2221ff00-a554-11e9-8cd7-240d9f671c8b.png)

**Comment by TimMcCauley** [comment]
@pathmapper this is a backend issue it seems, can you please add it to https://github.com/GIScience/openrouteservice ?
