### ISSUE TITLE
Suggestion: Add Hike bike map as layer map option

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice-app#20]
Message: Will you add as a layer map Hike bike map in the future?

**Comment by HendrikLeuschner** [comment]
Is this resolved by the new layerswitcher? Is the map included that you were talking about? @TimMcCauley

**Comment by TimMcCauley** [comment]
What he means is adding a hike map such as [thunderforest](https://www.thunderforest.com/maps/outdoors/), problem they cost. @TheGreatRefrigerator could you ask them nicely for free access for academia?
