### ISSUE TITLE
Distance markers every kilometre

### ISSUE THREAD

**Issue by MathieuHT** [GIScience/openrouteservice-app#201]
Hi everyone. It would make more sense and be more intuitive if the "Distance markers (km)" on the map were added every kilometre instead of every 500m (or alternatively add an option to choose the distance between markers), because it is confusing to have that many markers on the map (especially for long tracks) and have to calculate distances between markers. Thank you for your consideration.

**Comment by TheGreatRefrigerator** [comment]
Hi @MathieuHT, 
we discovered this some time ago too but didn't address this up to now. It's good to have an issue :+1: 
For this feature we currently use a plugin. I will be fixing this as soon as possible.
Also thinking of relating the waymarker distance to the zoom level.
