### ISSUE TITLE
export route doesn't save the newly added waypoints

### ISSUE THREAD

**Issue by gleysen** [GIScience/openrouteservice-app#202]
When I upload a new .gpx route, change some waypoints and then export the route again, it doesn't save my edits...
When I check the exported route, by uploading it again, it's the old route....
Is this a bug? Or am I doing something wrong?

**Comment by gleysen** [comment]
It seems like it might have exported it correctly, because when I imported it in Gaia GPS, it showed ok.
So perhaps it's just that it doesn't import it correctly... which is strange, because I exported it from openrouteservice.org in the first place.
I attached the exported .gpx track, it should normally be a 7,5 km route, but when I imported it yesterday it only showed about 5km, and when I tried it again just now it only draws 18m of it...
[Yttre-Bodane-final.gpx.zip](https://github.com/GIScience/openrouteservice-app/files/1847107/Yttre-Bodane-final.gpx.zip)

**Comment by TimMcCauley** [comment]
@gleysen I just tested this and can't reproduce your behaviour. I will consider this closed for now, please open it with more detail if you experience further details please.
