### ISSUE TITLE
Suggestion: add routeprofile for Special Vehicles (police, fire truck etc.)

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice-app#21]
Message: Bei der Routenplanung wäre vielleicht noch eine weitere Rubrik sinnvoll. "Sonderfahrzeuge" wie Polizei, Feuerwehr, Rettungsdienst - die auch Strecken nutzen dürfen, die für normale Autos gesperrt sind. 

(great google translating)
_In route planning, another section might be useful. "Special vehicles" such as police, fire brigade, rescue service - which can also use routes that are blocked for normal cars._

**Comment by TimMcCauley** [comment]
Moved to backend repository
