### ISSUE TITLE
Do not repeat distance units in axis tick labels of height profile graph

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice-app#219]
I believe the axis tick labels should contain just numbers, while the measure units itself should be rather displayed aggregated below or next to it, for example as `distance [km]`.

Current view
<img width="759" alt="image" src="https://user-images.githubusercontent.com/6545356/40001922-8a0b4996-578f-11e8-844b-2b99c03e5498.png">

Proposed change
<img width="756" alt="image" src="https://user-images.githubusercontent.com/6545356/40005892-5d966ce2-5799-11e8-9ef2-a06112176746.png">

**Comment by TheGreatRefrigerator** [comment]
This is a heightgraph plugin issue -> https://github.com/GIScience/Leaflet.Heightgraph

**Comment by TimMcCauley** [comment]
The plugin unfortunately is not maintained anymore but feel free to add the issue.

**Comment by aoles** [comment]
Thanks guys, moved this issue to https://github.com/GIScience/Leaflet.Heightgraph/issues/34.
