### ISSUE TITLE
Suggestion: waytype information for every profile

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice-app#22]
Message: Is there also a way to find out which parts of the route are along say a highway and
which on “normal” roads ?

essentially a request to implement the same waytype presentation, as we already have for the bicycle profile, for the Carprofile.

**Comment by TimMcCauley** [comment]
This is the "suitability" attribute for bikes/pedestrians and wheelchair, we might add it for the car profile in the future
