### ISSUE TITLE
Incorrect error/warning message when no location can be found

### ISSUE THREAD

**Issue by pathmapper** [GIScience/openrouteservice-app#220]
https://maps.openrouteservice.org/directions?n1=27.84085&n2=86.564294&n3=17&a=27.833089,86.651498,27.840243,86.564122&b=2&c=0&g1=-1&g2=0&k1=en-US&k2=km

Path in OSM:
https://www.openstreetmap.org/way/138505845#map=15/27.8273/86.5867

Also there is an error message "no internet connection" which is not correct: 
![image](https://user-images.githubusercontent.com/20856381/40007316-b5c022b6-579c-11e8-9331-21bb801a1b17.png)

**Comment by rabidllama** [comment]
Not sure why the route does not include that way, but the "internet not found" message is due to a 404 response when no location can be found (see https://github.com/GIScience/openrouteservice/issues/113). The error message should detect that a JSON response is returned saying that the address cannot be found and so show this information and not that there is no internet connection.

**Comment by sfendrich** [comment]
Graphhopper doesn't show the route geometry either: https://www.openstreetmap.org/directions?engine=graphhopper_foot&route=27.8313%2C86.6504%3B27.8399%2C86.5642#map=14/27.8272/86.6002. Maybe GH eliminates ways that traverse glaciers? Or it is due to trail_visibility=horrible?

**Comment by pathmapper** [comment]
@rabidllama @sfendrich thanks!

According to the following thread the way is not included because of `sac_scale=difficult_alpine_hiking` :
https://github.com/graphhopper/graphhopper/issues/766

Switching from walking to hiking includes this way for the route:

https://maps.openrouteservice.org/directions?n1=27.830841&n2=86.6078&n3=15&a=27.833089,86.651498,27.840243,86.564122&b=2b&c=0&g1=-1&g2=0&k1=en-US&k2=km

**Comment by TimMcCauley** [comment]
@pathmapper can you shift this to https://github.com/GIScience/openrouteservice ? We'll have a closer look at this and decide if we will consider this tag.

**Comment by pathmapper** [comment]
@TimMcCauley sure, some questions:

> decide if we will consider this tag

This tag is already considered using openrouteservice-app if "hiking" is choosen instead of "walking". Do you think about to consider it for "walking" also?

There is still a bug regarding the error/warning message, see also https://github.com/GIScience/openrouteservice-app/issues/220#issuecomment-389063317 from @rabidllama . I've changed the title of this issue to reflect this. Maybe reopen this issue to track this bug?

**Comment by TimMcCauley** [comment]
> This tag is already considered using openrouteservice-app if "hiking" is choosen instead of "walking". Do you think about to consider it for "walking" also?

Yes.

> There is still a bug regarding the error/warning message, see also #220 (comment) from @rabidllama . I've changed the title of this issue to reflect this. Maybe reopen this issue to track this bug?

True, will reopen, thanks!

**Comment by TheGreatRefrigerator** [comment]
The wrong warning message should be gone with the switch to Pelias endpoints.
Gonna rework the error messages to tackle issues https://github.com/GIScience/openrouteservice-app/issues/194 and https://github.com/GIScience/openrouteservice-app/issues/161 at some point.
