### ISSUE TITLE
Village found on OSM but not on ORS

### ISSUE THREAD

**Issue by pkubowicz** [GIScience/openrouteservice-app#224]
When searching for "Korzkiew" only 1 result is found. A village near Kraków (https://www.openstreetmap.org/relation/3274142) is not returned. The same search works fine on openstreetmap.org.

Points belonging to the village are resolved merely to addresses in the upper administrative level (like `Cmentarz parafialny, 32-088, Krakowski, Małopolskie, Poland`), even though OpenStreetMap has name set for the selected road (https://www.openstreetmap.org/way/511454367#map=18/50.16481/19.87638). To reproduce see https://maps.openrouteservice.org/directions?n1=50.162783&n2=19.877969&n3=16&a=50.086261,19.908609,50.164446,19.876499&b=0&c=0&k1=en-US&k2=km

**Comment by TimMcCauley** [comment]
@pkubowicz - thank you - we use pelias as a geocoder which will ne updated in the next month, most likely it will be found then.

**Comment by pkubowicz** [comment]
Don't you think it would be worth keeping this issue open so that we don't forget to verify it's resolved? Unless you keep this issue somewhere on your private list.

**Comment by TimMcCauley** [comment]
@pkubowicz if the issue persists after we upgrade, it will be have to be added to the pelias repository as an issue.

**Comment by aoles** [comment]
Re-opening to keep track of it.

**Comment by TimMcCauley** [comment]
@pkubowicz - could you please check if the results are the same? Thank you

**Comment by pkubowicz** [comment]
Searching maps.openrouteservice.org for "Korzkiew" still does not return any result. Address resolving still does not include the village name.

**Comment by TimMcCauley** [comment]
Ok interesting, this means it is a pelias issue - could you please add this example to their repository, in the same format as https://github.com/pelias/pelias/issues/728 ? Thanks a bunch

**Comment by pkubowicz** [comment]
Reported as https://github.com/pelias/pelias/issues/729
