### ISSUE TITLE
Review Polish translation

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice-app#226]
https://github.com/GIScience/openrouteservice-app/blob/development/app/languages/pl-PL.json

**Comment by TheGreatRefrigerator** [comment]
@aoles will you do this at some point 😬

**Comment by aoles** [comment]
Thanks for the reminder, I will get back to this soon.

**Comment by TheGreatRefrigerator** [comment]
@aoles will you do this at some point ?

**Comment by aoles** [comment]
There are a couple of issues with the Polish translation, such as untranslated English labels, so I will need to get to it soon..

**Comment by TheGreatRefrigerator** [comment]
A few years later...
maybe just add polish to the new client, i guess?
