### ISSUE TITLE
Suggests a route through highway=construction

### ISSUE THREAD

**Issue by pkubowicz** [GIScience/openrouteservice-app#227]
To reproduce see [this route](https://maps.openrouteservice.org/directions?n1=50.085276&n2=19.857799&n3=16&a=50.091898,19.865427,50.084222,19.845504&b=1a&c=0&g1=-1&g2=0&h2=3&k1=en-US&k2=km).

A route is suggested through [a way](https://www.openstreetmap.org/way/463832906) with `highway=construction` - so a road that does not exist yet. There is no possibility even for a pedestrian to follow this way, but the route is suggested for bike and car.

**Comment by TheGreatRefrigerator** [comment]
This is a backend related problem. Moved to https://github.com/GIScience/openrouteservice/issues/192
