### ISSUE TITLE
Update surface material encoding

### ISSUE THREAD

**Issue by rabidllama** [GIScience/openrouteservice-app#229]
In the update for the wheelchair profile, the surface material encoding within the extra info for "salt" (14) has been reassigned to "paving stones" as salt was very rarely used in OSM in comparison to paving stones which is much more important to portray for wheelchair routing.

**Comment by aoles** [comment]
What's the motivation behind reassigning an existing code rather than extending the code list by adding a new one?

**Comment by rabidllama** [comment]
because we are limited to 17 values in the encoder on the back end

**Comment by TimMcCauley** [comment]
It's worth mentioning that "salt" appears only 125 times in the OSM planet file

**Comment by aoles** [comment]
Fair enough - no more driving on salt then ;)

But if 17 is the magic number, how come we already have 18 in https://github.com/GIScience/openrouteservice-docs#surface ? (or even 19 if 0 counts as well)
