### ISSUE TITLE
zu viel Umwege?

### ISSUE THREAD

**Issue by gitka** [GIScience/openrouteservice-app#231]
Warum findet openrouteservice nicht den direkten Weg (Rennrad)? 
https://maps.openrouteservice.org/directions?n1=48.549754&n2=12.092385&n3=15&a=48.55322,12.104509,48.546473,12.079511&b=1c&c=0&g1=-1&g2=0&h2=3&k1=en-US&k2=km

In diesem Fall, wäre die direkte Strecke auch die schnellste und auch die kürzeste Strecke über Wohngebietsstrassen - egal mit welchem Radtyp. Nur mit "E-Bike" wird die direkte Strecke gefunden.

**Comment by TimMcCauley** [comment]
@gitka thank you for pointing this out - this is an issue of the routing engine - could you please add this to https://github.com/GIScience/openrouteservice ? Thanks a bunch
