### ISSUE TITLE
elevation plot (or Icon) missing when using mobile Browser

### ISSUE THREAD

**Issue by heinerolli** [GIScience/openrouteservice-app#234]
Hi; as already pointed out in the google group, the elevation plot (or Icon for plot in lower right corner) is missing on maps.openrouteservice.org when using Android or IOS Browser.
This is a real bummer, as it renders this great app/website useless during a bicycle tour. Whereas it otherwise has features which NO other routing App has - especially the avoid hills / set max steepness feature.
It would be great, if this issue could get priotized (and fixed) soon!

**Comment by heinerolli** [comment]
Hi;
I tried to test ‚it‘ - i.e.:

„it is now possible to set the visibility of the heightgraph from the settings.“

However, there is nothing in the settings to do toggle the heightgraph (or I am blind)

Can you pls clarify?

Thank you, Heiner

Von: Amandus<mailto:notifications@github.com>
Gesendet: Donnerstag, 9. August 2018 17:38
An: GIScience/openrouteservice-app<mailto:openrouteservice-app@noreply.github.com>
Cc: heinerolli<mailto:tanjaheiner@hotmail.com>; Author<mailto:author@noreply.github.com>
Betreff: Re: [GIScience/openrouteservice-app] elevation plot (or Icon) missing when using mobile Browser (#234)


Closed #234<https://github.com/GIScience/openrouteservice-app/issues/234> via d939576<https://github.com/GIScience/openrouteservice-app/commit/d939576d84f0a46617295f7b6f94aad13b830596>.

**Comment by TheGreatRefrigerator** [comment]
Hi @heinerolli,
These changes are still unreleased but will be live within the next days (hopefully tomorrow).
best regards
