### ISSUE TITLE
Village not found by its name without further information

### ISSUE THREAD

**Issue by pathmapper** [GIScience/openrouteservice-app#239]
The village **Ohiya** (https://www.openstreetmap.org/node/1752796346#map=15/6.8179/80.8429) is not found by its name.

Searching for **Ohiya, Badulla**, the village is found.

**Comment by TimMcCauley** [comment]
Thanks @pathmapper - can you please add this to the Pelias repository? This is the library we use - https://github.com/pelias/pelias many thanks .

**Comment by pathmapper** [comment]
@TimMcCauley done: https://github.com/pelias/pelias/issues/728.

Thanks for pointing me to the right repository!

**Comment by TimMcCauley** [comment]
You are welcome :-) good luck!!
