### ISSUE TITLE
Consult also openstreetmap records for Pelias admin-only queries?

### ISSUE THREAD

**Issue by pathmapper** [GIScience/openrouteservice-app#240]
@TimMcCauley assuming you are running an own instance of Pelias.

It looks like the villages not found in https://github.com/GIScience/openrouteservice-app/issues/224 and https://github.com/GIScience/openrouteservice-app/issues/239 are not issues with Pelias itself.

Instead the villages are not found because there are no corresponding areas in `whosonfirst` (further information in https://github.com/pelias/pelias/issues/728#issuecomment-403613051 and https://github.com/whosonfirst-data/whosonfirst-data/issues/1252).

It's kind of unexpected behavior that places visible on the ORS map are not found when searching for them. To avoid this,  would it be possible to use also `openstreetmap` records for the Pelias admin-only queries?

This would help also in cases where a place name is not found, because it is spelled differently in `openstreetmap` and `whosonfirst` (e.g. Rathnapura, https://github.com/pelias/pelias/issues/728#issuecomment-403820496).

**Comment by TimMcCauley** [comment]
@pathmapper they are issues of pelias which acts as an interface for openstreetmap/whosonfirst/geonames etcpp. if we were to add this behaviour, we would have to add it to pelias and according to Julian this is something they are trying to avoid as the osm data for administrative areas is quite noisy. I am closing this for now, I hope I could clarify this issue.

**Comment by pathmapper** [comment]
All right @TimMcCauley, thanks for your reply!
