### ISSUE TITLE
Map Error

### ISSUE THREAD

**Issue by neo13476** [GIScience/openrouteservice-app#241]
I have found an Map Error in maps.openrouteservice.org.

Wenn I am trying to find the adress "Lothringer Straße, Oberhausen", there is no result.

Then I haved tried to find the location on the map manually. The adress is named as:
Lothringer Straße, Styrum, Mülheim, Mülheim an der Ruhr , Nordrhein-Westfalen, Germany

Thats not correct. The street is located in the town "Oberhausen".  
The city border is marked correct a little south ...

On originally map on osm.org the location is correctly found at "Lothringer Straße, Oberhausen".
I can (I) solve problems like this?

Regards
Tobias

**Comment by alkino** [comment]
The openstreetmap data seems a bit outdated (~2 months) maybe an update could solve this.

**Comment by TimMcCauley** [comment]
@neo13476 @alkino we use pelias as a geocoder, please open an issue there - https://github.com/pelias/pelias
