### ISSUE TITLE
Custom API endpoint setting

### ISSUE THREAD

**Issue by TimMcCauley** [GIScience/openrouteservice-app#243]
Currently the app directs every request to the static setting `api.openrouteservice.org/..` - for a developer with a local ORS setup it would be handy, if the api endpoints could be changed in settings on the fly, so giving the user an option to send it to `localhost:8080/ors..` etc.

**Comment by TheGreatRefrigerator** [comment]
Closed by d939576d84f0a46617295f7b6f94aad13b830596
