### ISSUE TITLE
Frankfurt (Main) somehow wrongly related to Frankfurt (Oder)

### ISSUE THREAD

**Issue by SebAlbert** [GIScience/openrouteservice-app#244]
I hope this is a correct way of addressing what I think is a bug:

Searching for some address in Frankfurt (Main) as waypoint on the routing service (maps.openrouteservice.org) yields search results displaying "Frankfurt (Oder)" somewhere in the hierarchy. I could not reproduce this on openstreetmap.org, so I am not sure whether this is a problem in the data or in the way it is being used by the OpenRouteService.

See, as an example, https://i.imgur.com/tXXi9WU.png

**Comment by TimMcCauley** [comment]
@SebAlbert thank you for your message - we use Pelias as our geocoding service - could you therefore please report this [here](https://github.com/pelias/pelias), thank you

**Comment by missinglink** [comment]
@TimMcCauley This issue has now been fixed with the data provider in https://github.com/whosonfirst-data/whosonfirst-data/pull/1298.

The mismatched names issue should now be resolved on your next rebuild.

**Comment by TimMcCauley** [comment]
@missinglink many thanks - this is great news ;) !
