### ISSUE TITLE
Facilitate the opening of bike routing type dropdown

### ISSUE THREAD

**Issue by krichter722** [GIScience/openrouteservice-app#252]
Using the `openrouteservice-app` on a mobile device in a browser makes it very hard to open the bike routing type dropdown (touring/mountain/road bike) which also exist for heavy and pedestrian because the button is very small and thus hard to hit with the finger which is the usual input on smartphones. There's no zoom for the route planning form which might be a bug or a missing feature (although I see no need for it in the dropdown opening is facilitated).

Imo it's fine to make the 3 buttons for heavy vehicle, bike and pedestrian triggers to open the associated dropdown menu instead of the little triangle next to them.

experienced with 0.1.0-161-ge0e0511

**Comment by TimMcCauley** [comment]
We will soon be releasing a new maps client with this feature, therefor closing.

**Comment by nilsnolde** [comment]
I'll keep this open for reference

**Comment by TheGreatRefrigerator** [comment]
New client already replaced the classic one and is built for mobile devices (maps.openrouteservice.org)
