### ISSUE TITLE
Problem with car routing through hairpin curves

### ISSUE THREAD

**Issue by michalfabik** [GIScience/openrouteservice-app#254]
Hi, 
I've noticed that OpenRouteService fails to route through some particularly twisty hairpin curves on a mountain road: https://maps.openrouteservice.org/directions?n1=45.641243&n2=24.611027&n3=15&a=45.645908,24.605384,45.632646,24.61401&b=0&l2=1&l8=1&c=0&k1=en-US&k2=km  
  
After switching to bicycle routing, the route gets drawn correctly. I've checked the underlying OSM data and the road seems to be ok - the way is unbroken and there are no tags that would prohibit motor vehicle routing. JOSM doesn't report any errors, just two warnings about an unusual format of maxspeed=* (a common issue in Romania, given their legislation-based maxspeed tagging scheme).  
  
Regards,  
  
Michal

**Comment by marq24** [comment]
I will check it - but looks like there "something" in the OSM data that indicates that the road part is not suitable for a regular car...

see this "little" detour...
https://maps.openrouteservice.org/directions?n1=45.56785&n2=24.681559&n3=13&a=45.558475,24.603324,45.638385,24.606156&b=0&l2=1&l8=1&c=0&k1=en-US&k2=km

**Comment by marq24** [comment]
ok - I think I found the root cause... the section of the street that is not available in ORS is the section that is tagged with 

access:conditional=no @ (Nov-Jun)

**Comment by michalfabik** [comment]
Yeah, I noticed that tag too. But then, it's August now and it works for bicycle routing (the tag doesn't say anything about individual modes of transport, just general access).

**Comment by marq24** [comment]
for each vehicle type a different set of osm tags will be considered - some will be ignored

coming to 
access:conditional 

The current code does not allow to set a specific travel date (this is a feature that is currently under development) - this means currently the DATE that is used for the calculations, is the date of the data preparation - I don't know exactly when the last time the underlying graph data have been processed - but could be that it was in JUN...

Nevertheless - reverting the rule from 'no' to 'yes @ (JUL-OCT)' would be worth a try ;-)

**Comment by TimMcCauley** [comment]
@michalfabik @marq24 the last graphs were actually built in june.. we will be upgrading soon, so this will change.. sorry for the delay!
