### ISSUE TITLE
NPM 5.6 version no working of it.

### ISSUE THREAD

**Issue by asterixphp** [GIScience/openrouteservice-app#255]
My server installed node 8.11.4 version and npm 5.6 version.
In "npm install" processing have error and no install node_module.
What is the reason?
I write the error message.

root@ip-172-31-39-214:/var/www/html/openrouteservice-app# npm install
npm ERR! code EINTEGRITY
npm ERR! sha1-C0XMQgDkwwAPPkY1H9aa+FeCIPo= integrity checksum failed when using sha1: wanted sha1-C0XMQgDkwwAPPkY1H9aa+FeCIPo= but got sha1-cr7xGPeqozHb0ANjhEbQiPyiEAc=. (6402157 bytes)
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-31T14_12_59_354Z-debug.log

![image](https://user-images.githubusercontent.com/23121145/44917758-dd420f00-ad6b-11e8-8624-0b11ea89105e.png)
![image](https://user-images.githubusercontent.com/23121145/44917798-f480fc80-ad6b-11e8-8293-98895551413e.png)

**Comment by TimMcCauley** [comment]
Looks like a local hickup and nothing ors specific, closing this for now. @asterixphp if you can provide further info and need help please let us know.
