### ISSUE TITLE
GPX export strips out XML tag

### ISSUE THREAD

**Issue by rabidllama** [GIScience/openrouteservice-app#256]
It seems that the export as GPX option is not supplying the <?xml version="1.0" encoding="UTF-8" standalone="yes"?> tag in the gpx document which means that browsers cannot open the file. The ORS API adds this information correctly

See https://github.com/GIScience/openrouteservice/issues/168

**Comment by TheGreatRefrigerator** [comment]
New GPX generation is still buggy
