### ISSUE TITLE
Downloaded GPX file is corrupt

### ISSUE THREAD

**Issue by Toni-Reitz** [GIScience/openrouteservice-app#259]
Hi, Team of Open Route Service

After calculating a route on maps.openrouteservice.org and downloading a GPX file, the results seem to be corrupt. Eg. Routeconverter cannot read or modifiy the data. The problem exists for downloads with and without instructions, and can be replicated. 
  Please find attached two examples of corrupted output, without and with instructions.

Best wished to Heidelberg
Toni Reitz

[ors-export-linestring(18).zip](https://github.com/GIScience/openrouteservice-app/files/2384732/ors-export-linestring.18.zip)

P.S. There is a corresponding discussion in the google group. Unfortunately, the workaround advised there by Amandus does not help, as GPX-files with instructions seem to be corrupted, too.

**Comment by TheGreatRefrigerator** [comment]
Maps Version was reverted to v0.3.4 for old gpx output
It would be great if you could provide us with the name of applications you are using our gpx response on so we can make test the gpx files provided by our api with them.

**Comment by Toni-Reitz** [comment]
I use Routeconverter for editing, the komoot app as a backup on the android cellphone, and various Garmin Edge devices for navigating.
