### ISSUE TITLE
Problems installing openrouteservice-app 

### ISSUE THREAD

**Issue by ragapack** [GIScience/openrouteservice-app#261]
Hi,
I am trying install the openrouteservice-app on my Ubuntu 16.04.5 LTS
Before installing I update the system (apt-get update / apt-get upgrade)

First step Works fine:

git clone https://github.com/GIScience/openrouteservice-app.git
Second step too but I receive some Warnings
cd openrouteservice-app
npm install

root@ubuntu:/home/bitnami/openrouteservice-app# npm install

npm WARN deprecated @turf/line-distance@3.14.2: Module deprecated in favor of @t                                                                                        urf/length
npm WARN deprecated @turf/within@3.14.0: Module has been renamed to @turf/points                                                                                        -within-polygon
npm WARN deprecated leaflet-omnivore@0.3.4: This module is now under the @mapbox                                                                                         namespace: install @mapbox/leaflet-omnivore instead
npm WARN deprecated @turf/inside@3.14.0: Module has been renamed to @turf/boolea                                                                                        n-point-in-polygon
npm WARN deprecated polyline@0.2.0: This module is now under the @mapbox namespace: install @mapbox/polyline instead
npm WARN deprecated corslite@0.0.7: This module is now under the @mapbox namespace: install @mapbox/corslite instead
npm WARN deprecated togeojson@0.13.0: This module has moved: please install @mapbox/togeojson instead
npm WARN deprecated sexagesimal@0.5.0: This module is now under the @mapbox namespace: install @mapbox/sexagesimal instead
loadDep:socks-proxy-agent ▐ ╢█████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:socks-proxy-agent ▐ ╢█████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated bower@1.8.4: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated coffee-script@1.3.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
loadDep:urix → get        ▀ ╢███████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm WARN deprecated http2@3.3.7: Use the built-in module in node 9.0.0 or newer, instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
loadDep:cross-spawn → res ▀ ╢█████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm WARN prefer global jshint@2.8.0 should be installed with -g

After this executing the next command give me this error:
root@ubuntu:/home/bitnami/openrouteservice-app# node_modules/bower/bin/bower install
/usr/bin/env: ‘node’: No such file or directory

Any idea what is going wrong.?

**Comment by TheGreatRefrigerator** [comment]
Hi @ragapack,

The warnings are "normal". We currently are using some deprecated packages as it is a running system and we don't have the resources to focus this issue right now.

Your terminal doesn't know node. Check with `node -v` if it recognizes the command.
If it displays a version number it is another issue.
But it seems like you have to [add the node executable to your PATH variable](https://askubuntu.com/questions/881691/node-bash-path-confusion-on-ubuntu-16-using-n) or do [this](https://github.com/nodejs/node-v0.x-archive/issues/3911)

**Comment by ragapack** [comment]
Thank you for the fast answer
I resolved this step with
 ln -s /usr/bin/nodejs /usr/bin/node

Now at the end I have this problem
I copied my token to the weathercheck.txt file

bitnami@ubuntu:~/openrouteservice-app$ grunt ors
Loading "cachebust.js" tasks...ERROR
>> SyntaxError: Unexpected token ...
Warning: Task "cacheBust" not found. Use --force to continue.

Aborted due to warnings.


Execution Time (2018-10-05 10:48:40 UTC-0)
loading tasks  12.4s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100
Total 12.4s

An other question, can I define a port for the openrouteservice-app?
Thanks
Thomas

**Comment by ragapack** [comment]
The 1.6.0 version of   grunt-cache-bust works now for me
npm install grunt-cache-bust@1.6.0
Now it says:
Started connect web server on http://localhost:3035
But if I try to access my local server with
10.27.1.181:3035/
It says cannot reach the page


There are 2 Warnings I run the servisse with --force
Running "grunt:sliderMakeCss" (grunt) task
Spawning css task(s) in bower_components/angularjs-slider/Gruntfile.js
Warning: Task "css" not found. Use --force to continue.

Aborted due to warnings.


Execution Time (2018-10-09 12:17:38 UTC-0)
loading tasks  6.7s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 6.7s

Warning: Task "grunt:sliderMakeCss" failed. Used --force, continuing.

**Comment by TheGreatRefrigerator** [comment]
Try to access the local server in the browser with exactly:
http://localhost:3035
you don't have to replace localhost with your IP

Please make sure you did run `npm install` in the bower_components/angularjs-slider folder
(see https://github.com/GIScience/openrouteservice-app/#step-by-step-instructions)
and check in `bower_components/angularjs-slider/Gruntfile.js` if the task "css" exists.

then the `grunt:sliderMakeCss` should work.

**Comment by TheGreatRefrigerator** [comment]
Closing this for now. If other problems arise please reopen.
