### ISSUE TITLE
"Flying" Broken Image/Sleigh

### ISSUE THREAD

**Issue by tkan** [GIScience/openrouteservice-app#276]
Sorry, for the weird title but it is a weird bug/feature/easter egg I found. I'll copy from the [backend repo in which I posted the issue first by mistake](https://github.com/GIScience/openrouteservice/issues/412).

---
#### Here's what I did

Planning a route from Salzburg to Leipzig, added a 'via point' to go through Prague (happened regardless of the placement of the origin, via and end point though). As the route computation is done, a broken image starts "flying" from Paris to Kiev.
#### Here's what I got

I recorded an example "flight": https://streamable.com/7rrrd

The HTML of the affected element:
`<img src="https://maps.openrouteservice.org/images/marker-icon.png" class="leaflet-marker-icon leaflet-zoom-animated leaflet-interactive" style="margin-left: -12px; margin-top: -41px; width: 25px; height: 41px; transform: translate3d(2397px, 370px, 0px); z-index: 370;" alt="" tabindex="0">`

The `translate3d(2397px, 370px, 0px)` can be observed as changing as the animation progresses.
#### Here's what I was expecting

Well, no flying images. ;)
#### Further information

Not reproducible on Chromium (same machine).

Used Browser:
Firefox 65.0.1, Linux 4.20.7-arch1-1-ARCH
with extensions:

```
Cookie AutoDelete
Decentraleyes (tested with activated and deactivated status)
Disable WebRTC
DuckDuckGo Privacy Essentials
I don't care about cookies (tested with activated and deactivated status)
LeechBlock NG
Mind the Time
minimal
Offline QR Code Generator
Old Reddit Redirect
OneTab
Shut Up: Comment Blocker
uBlock Origin
```
---

I don't understand what is going on. The webapp uses (for what reason I can only wonder) the [MovingMarker](https://github.com/ewoken/Leaflet.MovingMarker) plugin. In the build code of the webapp ([scripts[…].js](https://maps.openrouteservice.org/scripts.ff2acea2e9b40ca0.js)) there is the following code which can not be found in the repo:

```
var movingSleigh = L.Marker.movingMarker([[48.8567, 2.3508],[50.45, 30.523333]],[20000]).addTo($scope.mapModel.geofeatures[actionPackage.layerCode]);
movingSleigh.start();
```

So Paris and Kiev as well as the animation are definitely not at random in the code. Someone wanted to have an animated … … sleigh? From Paris to Kiev? o_O

**Comment by pathmapper** [comment]
> have an animated … … sleigh

@tkan good find!

IIRC there was some animation with snowflakes on the map during christmas time, don't remember a sleigh though, but it could be a leftover of this Christmas gimmick.

**Comment by TimMcCauley** [comment]
@tkan @pathmapper sorry about this and thanks for pointing it out - I removed the code causing this just then; could you please clear your cache and check again? thanks :)

**Comment by tkan** [comment]
@TimMcCauley 
yes, no phantom sleigh in sight. ;) solved, I'd say.
