### ISSUE TITLE
Error message wheelchair routing outside Europe

### ISSUE THREAD

**Issue by pathmapper** [GIScience/openrouteservice-app#277]
According to https://github.com/GIScience/openrouteservice/issues/413#issuecomment-464657171

>  wheelchair routing is only available within Europe

This is currently not clear because the UI offers wheelchair routing outside Europe and the error message is: `Code 2010: Point 0 is out of bounds.`

![image](https://user-images.githubusercontent.com/20856381/52944185-23694a00-336f-11e9-9ff7-a94ca92a38bd.png)

**Comment by TimMcCauley** [comment]
We will soon be serving wheelchair for the globe; thus closing this issue.

**Comment by nilsnolde** [comment]
Globe won't build for a long while I think.

The ORS error message is correct however, so I won't re-open. We should make it clear somewhere that wheelchair is Europe only. Any suggestion @TheGreatRefrigerator ?

**Comment by TheGreatRefrigerator** [comment]
I will add a flag to inform the user
