### ISSUE TITLE
Routing url miss match with the backend

### ISSUE THREAD

**Issue by pingrunhuang** [GIScience/openrouteservice-app#281]
Currently, I'm trying to route to my local openrouteservice by changing the Gruntfile.js. Seems like the routing parameters are miss-matching with the backend URL. 
- app request
```
curl http://localhost:8082/v2/directions\?attributes\=detourfactor%7Cpercentage\&coordinates\=116.529236,39.967122%7C116.554298,39.930801\&elevation\=true\&extra_info\=steepness%7Cwaytype%7Csurface\&geometry\=true\&geometry_format\=geojson\&instructions\=true\&instructions_format\=html\&language\=en-US\&preference\=fastest\&profile\=driving-car\&units\=m
```
However, the backend require the request to have the profile in the endpoint. Also the starting and ending point parameter are wrong.
Am I missing something?

**Comment by TimMcCauley** [comment]
Greetings @pingrunhuang,

this application consumes the old version of the API. Can you please remove the `v2` and try again? 

```http://localhost:8082/ors/routes?...```

**Comment by pingrunhuang** [comment]
Not sure which version you are running on for backend ors. For me, I saw [the source code](https://github.com/GIScience/openrouteservice/blob/e23e9ced3e3e4015334714378138db7043983135/openrouteservice/src/main/java/heigit/ors/api/controllers/RoutingAPI.java#L45) indicating the endpoint seems to be not what you claimed. 
I am running the master version, please tell me if I am wrong.

**Comment by TimMcCauley** [comment]
That is correct and what I mean above is that the openrouteservice-app client does not consume this version of the API which we call `v2`, it uses one previous version, please select `v1` here https://openrouteservice.org/dev/#/api-docs/directions

**Comment by pingrunhuang** [comment]
But I want the openrouteservice-app to consume my local backend which is using the v2 version. And I don't see any endpoint for v1 exists in the source code of ors backend, how come the app client could visit the v1 endpoint?
Am I missing something here? If so, could you tell me the whole process of setting the client and local backend?

**Comment by TimMcCauley** [comment]
@pingrunhuang openrouteservice-app does not consume the `v2` backend, as already stated above, it uses the previously implemented API using tomcat only without spring -> https://github.com/GIScience/openrouteservice/tree/master/openrouteservice/src/main/java/heigit/ors/services/routing the API documentation I posted above and to run ORS locally please use these instructions: https://github.com/GIScience/openrouteservice

**Comment by pingrunhuang** [comment]
@TimMcCauley Thanks a lot for your help!

**Comment by TimMcCauley** [comment]
You are welcome!
