### ISSUE TITLE
Deploy over HTTPS

### ISSUE THREAD

**Issue by russellhoff** [GIScience/openrouteservice-app#283]
Is there any way to deploy the web app via 443 port, plus using a certificate (we've got letsencrypts' certificates)?

We don't any such a wide experience in grunt, so any help is appreciated.

Thanks!

**Comment by TimMcCauley** [comment]
Hi @russellhoff - you could stick the web-app behind apache consuming your certificates.

**Comment by russellhoff** [comment]
@TimMcCauley Is there any resource to learn how to deploy the app to apache httpd? Thanks a lot!

**Comment by TimMcCauley** [comment]
@russellhoff maybe this will help you: https://www.youtube.com/watch?v=p90yWh26j94
