### ISSUE TITLE
Strange Heatmap

### ISSUE THREAD

**Issue by geovista116** [GIScience/openrouteservice-app#286]
Dear OpenRouteService,

We have some issues with isochrone generation with 3 points. Some fringe appears along street that no exist in OSM. I have just attached some screenshots.

![isocrones_openrouteservice_v3](https://user-images.githubusercontent.com/51724737/59802832-6ac8fe00-92af-11e9-948c-d79e0a5e1926.png)

![isocrones_openrouteservice_v2](https://user-images.githubusercontent.com/51724737/59801794-15402180-92ae-11e9-9303-7bc23b53b204.png)

![isocrones_openrouteservice](https://user-images.githubusercontent.com/51724737/59801796-15d8b800-92ae-11e9-9c4c-026751fa267a.png)

![qgis-ltr-bin_iBXuff0qUi](https://user-images.githubusercontent.com/51724737/59802388-97304a80-92ae-11e9-886f-c0e91e280478.png)

best regards, 

Vincent

**Comment by TimMcCauley** [comment]
@geovista116 thank you for sharing this, would you mind adding this issue to the backend repository https://github.com/GIScience/openrouteservice ? It will be looked into then. Thanks!

**Comment by geovista116** [comment]
Ok, just did. Sorry for mistake...
