### ISSUE TITLE
Handle way smoothness

### ISSUE THREAD

**Issue by pkubowicz** [GIScience/openrouteservice-app#287]
I'm not sure if routing profiles take smoothness into account, but even if it is used, it is not visible to user.

Use case: currently maps.openrouteservice.org show surface type distribution of the selected route, which is enormously helpful. However, OpenStreetMap has only 1 surface type for 'asphalt', wile in reality this is a very broad idea, ranging for a perfectly flat surface to a road that is half way in disintegrating into gravel - and cannot be driven on a sports car or a road bike. Currently planning a trip using mapsopenrouteservice.org is risky, because a 100% asphalt route can be so bad that it's not possible to follow it.

OpenStreetMap wiki suggests renderers should use [key:smoothness](https://wiki.openstreetmap.org/wiki/Key:smoothness) to determine usability for different wheel vehicles.

I am not suggesting to show full range of smoothness values to the user, it would probably be too many parameters. When I see surface distribution, I would like to have more categories than just 'asphalt'. Maybe 'bad asphalt' for 'asphalt' + smoothness 'bad' or below and old 'asphalt' for other combinations (surface=asphalt plus smoothness=intermediate or surface=asphalt + no smoothness set).

An alternative is to use [key:tracktype](https://wiki.openstreetmap.org/wiki/Key:tracktype), but the wiki say it is rarely set for roads.

**Comment by TimMcCauley** [comment]
Thank you @pkubowicz - could you please move thie issue over to our backend which is https://github.com/GIScience/openrouteservice thank you
