### ISSUE TITLE
Integration with pelias, openpoiservice

### ISSUE THREAD

**Issue by OleMussmann** [GIScience/openrouteservice-app#289]
For a fully offline deployment, how to integrate `openrouteservice-app` with
- pelias (geocode)
- openpoiservice (pois)
- mapsurfer
- landmarks
- fuel
- shortenlink(?)

Basically: How can one re-build and deploy your wonderful service https://maps.openrouteservice.org offline?

**Comment by TimMcCauley** [comment]
Hi @OleMussmann - you would have to combine all the repositories into a - e.g. docker setup (docker-compose file) - which would obviously take some time and effort.
