### ISSUE TITLE
Improve feedback for issue reporter

### ISSUE THREAD

**Issue by krichter722** [GIScience/openrouteservice-app#296]
I noticed that some issues are closed without providing clear information when the issue is fixed. In these cases a developer drops a line like "This will be closed in the upcoming release" and closes the issue. Usually an issue is closed when it's merged into the development branch. It's nice to know that you plan to fix the issue, but contributors can keep track of the progress much easier if the issue is closed when it's actually fixed, e.g. in the commit message.

Examples:
* https://github.com/GIScience/openrouteservice-app/issues/137
* https://github.com/GIScience/openrouteservice-app/issues/252

**Comment by pathmapper** [comment]
Here is another example of a closed issue where the issue is still present on https://maps.openrouteservice.org :

- https://github.com/GIScience/openrouteservice-app/issues/277

**Comment by nilsnolde** [comment]
On some you're right, on some not;)

We'll add some updates to the README. Basically, geocoding issues don't belong in this issue tracker. It's not the tracker for https://maps.openrouteservice.org, but for the web app, of which our map instance is just one instance. 

Please use https://ask.openrouteservice.org for issues with our live maps web app.
