### ISSUE TITLE
Improve address search

### ISSUE THREAD

**Issue by krichter722** [GIScience/openrouteservice-app#297]
If one enters an almost complete or even complete address, the suggestions are sometimes very unrelated and sometimes misleading.

Examples:
* Enter `10787 Keithstraße 2` which is a ZIP code 10787 and an address `Keithstraße 2`: You get five numbers in Keithstraße, but none of them is 2. If there's a direct match, it should be displayed as first result
* Enter `Keithstraße 2, Berlin` yields the only result
    ```
    Keithstraße 2
    12307, Lichtenrade, Tempelhof-Schoneberg, Berlin, Berlin, Germany
    ```
    which is very misleading because there're two Keithstraße 2 in Berlin in different districts (smart, right?) and both should be displayed (in the worst case a user interprets the only result as the fact that there's only one street with that address).
* Entering `Gubener Str. 40, 10243` allows to identify an address correctly since the ZIP code identifies the city, but it yields
    ```
    Gubener Straße 40
    Gelsenkirchen, Gelsenkirchen , Nordrhein-Westfalen, Germany
    Gubener Straße 40
    40627, Dusseldorf, Düsseldorf , Nordrhein-Westfalen, Germany
    ```
    which has much less to do with the exact match `Gubener Str. 40, 10243 Berlin` which isn't displayed at all.

I'm aware that this confusion might be caused by regional address forms, but as a user I simply _don't want you to make me think_.

maps.openstreetmap.org has this figured out, you can probably take over their logic.

**Comment by pathmapper** [comment]
ORS uses an own instance of Pelias for geocoding ([source](https://ask.openrouteservice.org/t/about-the-opengeocoder-category/16)) and querying the Pelias reference server gives for all three cases the expected result:

`10787 Keithstraße 2`
https://pelias.github.io/compare/#/v1/search%3Ftext=10787%20Keithstra%C3%9Fe%202

`Keithstraße 2, Berlin`
https://pelias.github.io/compare/#/v1/search%3Ftext=Keithstra%C3%9Fe%202,%20Berlin

`Gubener Str. 40, 10243`
https://pelias.github.io/compare/#/v1/search%3Ftext=Gubener%20Str.%2040,%2010243

So there might be something wrong with the ORS Pelias instance or the used data (data should be the same as used for the Pelias reference server according to this [post](https://ask.openrouteservice.org/t/structured-geocode-wrong-coordinates-for-address/919/4)).

@nilsnolde any idea?

**Comment by nilsnolde** [comment]
Thanks @krichter722 and @pathmapper for the digging. Jep, data should be pretty much the same. Our dump is 4-5 weeks old.

However, our Pelias software stack is as old. Their reference server usually runs the latest & greatest. Could be the reason. I'll upgrade this week and report back.

@krichter722 for future reference: If you could paste the URLs used to find an address that'd much speed up our end. In the developer tab of your browser (usually CTRL + SHIFT + I), you can see the request in the `Network` tab, it always starts with `search?`. If you copy the `Request URL` you see on the right next time, that'd be superb:)

![image](https://user-images.githubusercontent.com/25637358/64506857-ba80f980-d2e1-11e9-9564-253dc1cefe45.png)

**Comment by nilsnolde** [comment]
FYI: I updated all Pelias repos on the server to the lastest and restarted all services. No difference in results as far as I can see.

A little too lazy now to research if it could be an OSM issue (which I doubt anyways), so it might be a config issue. I'm lacking the time to dig in properly as of now. A lot changed in the last 5-6 months on Pelias config and I still use a config (with minor changes) from a year ago. 

I won't forget though.

**Comment by pathmapper** [comment]
Thanks for the update and info.

Just checked https://ask.openrouteservice.org/t/street-in-hannover-not-found/925 and it looks like for this query there is also no difference in the result.

`https://api.openrouteservice.org/pgeocode/search?api_key=5b3ce3597851110001cf62481bd87c3b86064ab2941f0564b1dac59d&focus.point.lat=49.40946539077921&focus.point.lon=8.693017959594728&lang=en-US&size=5&text=carl-neuberg-stra%C3%9Fe+hannover`

**Comment by nilsnolde** [comment]
Ok, should be better now. All queries work now.
