### ISSUE TITLE
Turn-Restriction ignored

### ISSUE THREAD

**Issue by jschleic** [GIScience/openrouteservice-app#304]
Why does ORS ignore the turn-restriction [6013835](https://www.openstreetmap.org/relation/6013835) in the following routing [request](https://maps.openrouteservice.org/directions?n1=48.739033&n2=9.301434&n3=17&a=48.73996,9.299111,48.739069,9.300077&b=0&c=0&k1=en-US&k2=km)?
GraphHopper and [OSRM](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.73981%2C9.29901%3B48.73898%2C9.30051#map=18/48.73987/9.29866) route correctly.

**Comment by TheGreatRefrigerator** [comment]
Hi @jschleic,

This is because by default the algorithm used is not including turn restrictions in the calculation.
(see https://ask.openrouteservice.org/t/route-ignores-no-right-turn-restriction/220/3)

You can use a workaround by setting avoid ferries for example.

**Comment by TheGreatRefrigerator** [comment]
This should be working now:
https://ask.openrouteservice.org/t/route-ignores-no-right-turn-restriction/220/10
