### ISSUE TITLE
Set route weightings is ignored and zeroed

### ISSUE THREAD

**Issue by MichaelsJP** [GIScience/openrouteservice-app#309]
When I set the route `weightings` for `green` and `quiet` by hand e.g. `0.8` (see image) it's ignored and in the end zeroed. When I use the app `up and down keys` the values are set to integers (see image) instead of decimal values, even though the explanations state the values should be decimals.

So the example below would result in: `{"weightings":{"green":4,"quiet":0}}` instead of `{"weightings":{"green":4,"quiet":0.8}}`

![image](https://user-images.githubusercontent.com/22392104/72222777-c703b000-3568-11ea-8d14-516c86de4d64.png)

**Comment by TheGreatRefrigerator** [comment]
This is a problem with the playground. I recreated the issue in the ors-website repository.
https://gitlab.gistools.geog.uni-heidelberg.de/giscience/openrouteservice-infrastructure/ors-website/issues/91
