### ISSUE TITLE
Deleting last way point element

### ISSUE THREAD

**Issue by MichaelsJP** [GIScience/openrouteservice-app#312]
When I hit the delete button in single way point element in the round trip mode, it deletes it completely instead of just emptying it.

![image](https://user-images.githubusercontent.com/22392104/73081801-8b51da00-3ec8-11ea-9945-b2477182c74b.png)

**Comment by TheGreatRefrigerator** [comment]
Thank you for this amazing drawing. You should have taken art classes.
