### ISSUE TITLE
HGV Params slider step

### ISSUE THREAD

**Issue by russellhoff** [GIScience/openrouteservice-app#324]
I wish I'd move HGV parameters' sliders halves by halves, instead of having steps of 1 units. As [official sample page](http://angular-slider.github.io/angularjs-slider/) says, this can be done by:

```
$scope.slider = {
  value: 0.5,
  options: {
    floor: 0,
    ceil: 2,
    step: 0.1,
    precision: 1
  }
};
```

To introduce this in openrouteservice-app, I've edited `./app/constants/lists.js` and edited the following:

```
hgvParams: {
      height: {
        min: 2,
        max: 50,
        value: "height",
        options: {
          step: 0.5
        }
      },
}
```

But it doesn't work, as the steps remain being one by one.

What am I doing wrong?

Thanks

**Comment by TheGreatRefrigerator** [comment]
Hi @russellhoff,

You will have to also apply this value during the initialization of the sliders.
Look at ors-options.js from line 333 onwards.
you can put the `step` value directly into the `height` object in lists.js.
The `ceil` and `floor` values are also mapped to `min` and `max`.
But i think you will get the idea when you look at that file.

Feel free to do a pull request. I will review it.

**Comment by TheGreatRefrigerator** [comment]
fixed in new client https://github.com/GIScience/ors-map-client/commit/84a9ee9a6213f2f3f1944ec90f70804b44958e4d
