### ISSUE TITLE
Allow custom background

### ISSUE THREAD

**Issue by joostschouppe** [GIScience/openrouteservice-app#331]
Just a feature request:
I'm not aware of any routeplanner where you can add a custom overlay or background map. My usecase is: "plan a route to actively avoid areas with mapillary coverage", but I can imagine loads of other usecases (e.g. try to route as close as possible to roads alreadye exisitng on this 1873 basemap, haha) . It would of course be awesome to have an automatic routing service for that job, but that's more complicated by an order of magnitude I suppose.

**Comment by TheGreatRefrigerator** [comment]
@joostschouppe : is this open source?
You are talking about this coverage:https://www.mapillary.com/examples/tiles/map-leaflet
correct?

**Comment by sfendrich** [comment]
@joostschouppe As long as you have the mapillary data available, the coverage use case should be possible with any route planner with only minor modifications of the data import. E.g., you could use a route planner that considers traffic and model the coverage as high traffic. If it is sufficient to avoid certain areas, then you could use ORS' avoid polygons.

For the 1873 use case you need a routable street network graph of your base map. Then you could route on this graph and use map matching to fit the route to the modern map.

**Comment by joostschouppe** [comment]
I'll ask Mapillary itself to comment on the license of the tile layer and availability of data to input into routing choices
@sfendrich : my suggested solution is based on some leaflet edits (which is of the level of things I can do myself), "minor modifications of data import" is something I hope to be able to do one day (but only because I'm a dreamer). And yeah, there's no 1873 routable network I can think of; my point was rather "people have all these weird things they would like to consider when clicking together a route". Often, visual cues are enough for a human to play with some waypoints to get the route to do what they want. So any route planner that has the option to let people add their own extra layer would be interesting for all sorts of people with niche interests.

**Comment by cbeddow** [comment]
@joostschouppe you are free to use all the Mapillary tile layers. 🙂 Also, you can freely use the Mapillary images API to get all the images in a bbox, just register a client ID at mapillary.com/developer.

Try: `https://a.mapillary.com/v3/images?client_id=YOURCLIENTID&bbox=lon1,lat1,lon2,lat2`

For example get all images in Bruges. Then it's a geojson response, with the point locations of images. V3/sequences API returns lines. With either you could then add a buffer around the points/lines, then I believe the routing API accepts a geojson layer (polygons now) as an exception to the route, or maybe that geojson layer becomes weighted negatively in the routing decision.

**Comment by joostschouppe** [comment]
Just an FYI for anyone wanting the same feature: in the [BRouter webtool](https://brouter.de/brouter-web/) you can do this by adding this URL `https://d6a1v2w10ny40.cloudfront.net/v0.1/{z}/{x}/{y}.png` as a custom overlay.

**Comment by koebi** [comment]
Hey,
this client is no longer being actively developed.
[Our new client](https://maps.openrouteservice.org/#/) also has this feature, you can find it via the "Settings"-Button (the cogwheel in the left sidebar, top right), under "Advanced".

**Comment by joostschouppe** [comment]
Nice! Thanks for the tip
