### ISSUE TITLE
Travel times - Info request

### ISSUE THREAD

**Issue by ro-del** [GIScience/openrouteservice-app#339]
Dear Sirs,
I would like to know how travel times are calculated, I mean if they are average travel times, in generic times and standard conditions, or they are contextualised to the current traffic, also depending on works and restrictions that can occur on the routes.
For example, in this moment, this is the case of Genova's surroundings in Italy.
I need to know in order to use the data properly.
Many thanks for your help.
Best wishes,
Roberta

**Comment by TheGreatRefrigerator** [comment]
Hi @ro-del,

Please see this post in our forum and check out the table in the link provied there.
https://ask.openrouteservice.org/t/travel-time-calculation/1738

Best regards

**Comment by ro-del** [comment]
Thank you!
Can you also tell me how population in the catchement area is calculated?
Best regards

**Comment by TheGreatRefrigerator** [comment]
please use the forum for this.
this is not calculated by this client itself but only passed to it by the ORS backend.
Best regards

**Comment by ro-del** [comment]
ok, sorry
