### ISSUE TITLE
Affichage de l'altitude

### ISSUE THREAD

**Issue by Nekonato** [GIScience/openrouteservice-app#349]
La courbe de variation de l'altitude ne s'affiche plus dans rubrique "informations supplémentaires" (itinéraire vélo ou pédestre)

**Comment by TheGreatRefrigerator** [comment]
Hi @Nekonato,
That is indeed correct. It seems to be an issue with the ors backend.
The request still contains the the `extra_info: steepness` but it is not returned.

Please track the backend issue here: https://github.com/GIScience/openrouteservice/issues/843

**Comment by Nekonato** [comment]
Hello.
The problem has been solved and the bug is now fixed.
Thank you for your help.
We use maps.openrouteservice.org to prepare a four months bicycle trip
around France from the end of may to the end of september. It's such a good
thing to have this wonderful tool.
*THANK YOU.*
Bertrand.
