### ISSUE TITLE
Add numbers to each route stop on the leaflet map

### ISSUE THREAD

**Issue by thibaultmol** [GIScience/openrouteservice-app#350]
Being able to see on the map in what order the stops are is a big thing I'm missing atm.
(I'm referring to openrouteservice.org/map which I assume this is the correct repo of)

**Comment by TheGreatRefrigerator** [comment]
Hi, i just also answered your forum post :)

For the new maps client (openrouteservice.org/map) please create an issue in the [new maps client repo](https://github.com/GIScience/ors-map-client/issues/new)

best regards
