### ISSUE TITLE
'Unknown search place error' when typing 'niepołomice'

### ISSUE THREAD

**Issue by pkubowicz** [GIScience/openrouteservice-app#354]
To reproduce:
1. Open https://maps.openrouteservice.org
2. Type (or paste) `niepołomice`

An error message appears: `Unknown search place error`

JavaScript console:
```
TypeError: e[1].features[0] is undefined simple-place-search.js:301:16
```
(Firefox 86.0)

Pelias is able to search for this text: https://pelias.github.io/compare/#/v1/search?text=niepo%C5%82omice

**Comment by TheGreatRefrigerator** [comment]
Hi @pkubowicz,

this is the repository for the https://classic-maps.openrouteservice.org page
you can find the other one on:
https://github.com/GIScience/ors-map-client

I could not reproduce the error though.
Pasting and typing both work.
is this still a problem?

**Comment by pkubowicz** [comment]
Today it works fine. I'm closing the issue.
