### ISSUE TITLE
uglify:generated error task

### ISSUE THREAD

**Issue by stefanocudini** [GIScience/openrouteservice-app#359]
show this at first docker-compose up

Running "uglify:generated" (uglify) task
ors-maps            | JS_Parse_Error [SyntaxError]: Invalid assignment
ors-maps            |     at JS_Parse_Error.get (eval at <anonymous> (/ors-classic-maps/node_modules/grunt-contrib-uglify/node_modules/uglify-js/tools/node.js:18:1), <anonymous>:69:23)
ors-maps            |     at formatError (internal/util/inspect.js:1164:38)
ors-maps            |     at formatRaw (internal/util/inspect.js:937:14)
ors-maps            |     at formatValue (internal/util/inspect.js:791:10)
ors-maps            |     at inspect (internal/util/inspect.js:328:10)
ors-maps            |     at formatWithOptions (internal/util/inspect.js:1989:40)
ors-maps            |     at console.value (internal/console/constructor.js:308:14)
ors-maps            |     at console.log (internal/console/constructor.js:343:61)
ors-maps            |     at /ors-classic-maps/node_modules/grunt-contrib-uglify/tasks/uglify.js:144:17
ors-maps            |     at Array.forEach (<anonymous>) {
ors-maps            |   filename: '../.tmp/concat/vendor.js',
ors-maps            |   line: 77150,
ors-maps            |   col: 240,
ors-maps            |   pos: 2557402
ors-maps            | }

**Comment by TheGreatRefrigerator** [comment]
Hi @stefanocudini,

yes, the build is currently broken, probably due to some version mismatching.
Sadly, i currently don't have any time to investigate and work on this, as it is not high priority -.-
I appreciate any help you can give in tracking down the actual issue. Also PRs are welcome.

Best regards

**Comment by TheGreatRefrigerator** [comment]
This also only happens within the docker container, when installing dependencies locally, uglify is working fine.

**Comment by TheGreatRefrigerator** [comment]
https://giters.com/zenorocha/clipboard.js/issues/737?amp=1

Seems clipboard js has pushed some arrow function into the production distribution -.-

will push a fix tomorrow
