### ISSUE TITLE
Trouble installing, teleborder missing.

### ISSUE THREAD

**Issue by st3inar** [GIScience/openrouteservice-app#365]
I have trouble with installing the app via docker on windows. Seems like https://github.com/Teleborder is not available any more.
See error at the end. Any suggestions? 

> C:\Git\openrouteservice-app>docker compose build
[+] Building 14.6s (10/12)
 => [internal] load build definition from Dockerfile                                                                                                                                   0.0s
 => => transferring dockerfile: 32B                                                                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                                        0.0s
 => [internal] load metadata for docker.io/timbru31/node-alpine-git:12                                                                                                                 2.3s
 => [1/8] FROM docker.io/timbru31/node-alpine-git:12@sha256:33630b41516905abf5563fc59bf9a5f850847e537c5d3fb3e346b729f6d4a24f                                                           0.0s
 => [internal] load build context                                                                                                                                                      0.1s
 => => transferring context: 11.45kB                                                                                                                                                   0.0s
 => CACHED [2/8] COPY [.bowerrc, bower.json, bs-config.js, main.js, package.json, package-lock.json, /ors-classic-maps/]                                                               0.0s
 => CACHED [3/8] RUN cd /ors-classic-maps                                                                                                                                              0.0s
 => CACHED [4/8] WORKDIR /ors-classic-maps                                                                                                                                             0.0s
 => CACHED [5/8] RUN npm install                                                                                                                                                       0.0s
 => ERROR [6/8] RUN NODE_MODULES/BOWER/BIN/BOWER install --allow-root                                                                                                                 12.1s
------
 > [6/8] RUN    NODE_MODULES/BOWER/BIN/BOWER install --allow-root:
#0 1.149 bower leaflet-distance-markers#*       not-cached https://github.com/adoroszlai/leaflet-distance-markers.git#*
#0 1.151 bower leaflet-distance-markers#*          resolve https://github.com/adoroszlai/leaflet-distance-markers.git#*
#0 1.386 bower angular-cookies#~1.5.10          not-cached https://github.com/angular/bower-angular-cookies.git#~1.5.10
#0 1.386 bower angular-cookies#~1.5.10             resolve https://github.com/angular/bower-angular-cookies.git#~1.5.10
#0 1.388 bower font-awesome#^4.6.3              not-cached https://github.com/FortAwesome/Font-Awesome.git#^4.6.3
#0 1.388 bower font-awesome#^4.6.3                 resolve https://github.com/FortAwesome/Font-Awesome.git#^4.6.3
#0 1.390 bower leaflet.editable#^1.0.0          not-cached https://github.com/yohanboniface/Leaflet.Editable.git#^1.0.0
#0 1.390 bower leaflet.editable#^1.0.0             resolve https://github.com/yohanboniface/Leaflet.Editable.git#^1.0.0
#0 1.392 bower angular-sanitize#1.5.9           not-cached https://github.com/angular/bower-angular-sanitize.git#1.5.9
#0 1.392 bower angular-sanitize#1.5.9              resolve https://github.com/angular/bower-angular-sanitize.git#1.5.9
#0 1.409 bower angular-tooltips#^1.1.8          not-cached https://github.com/720kb/angular-tooltips.git#^1.1.8
#0 1.409 bower angular-tooltips#^1.1.8             resolve https://github.com/720kb/angular-tooltips.git#^1.1.8
#0 1.410 bower d3-tip#v0.7.1                    not-cached https://github.com/Caged/d3-tip.git#v0.7.1
#0 1.410 bower d3-tip#v0.7.1                       resolve https://github.com/Caged/d3-tip.git#v0.7.1
#0 1.412 bower leaflet.markercluster#^1.0.3     not-cached https://github.com/Leaflet/Leaflet.markercluster.git#^1.0.3
#0 1.412 bower leaflet.markercluster#^1.0.3        resolve https://github.com/Leaflet/Leaflet.markercluster.git#^1.0.3
#0 1.413 bower jquery-ui#^1.12.0                not-cached https://github.com/components/jqueryui.git#^1.12.0
#0 1.413 bower jquery-ui#^1.12.0                   resolve https://github.com/components/jqueryui.git#^1.12.0
#0 1.414 bower rxjs#*                           not-cached https://github.com/Reactive-Extensions/RxJS.git#*
#0 1.415 bower rxjs#*                              resolve https://github.com/Reactive-Extensions/RxJS.git#*
#0 1.416 bower angular-translate#2.13.0         not-cached https://github.com/PascalPrecht/bower-angular-translate.git#2.13.0
#0 1.416 bower angular-translate#2.13.0            resolve https://github.com/PascalPrecht/bower-angular-translate.git#2.13.0
#0 1.433 bower vkBeautify#*                     not-cached https://github.com/kayhadrin/vkBeautify.git#*
#0 1.433 bower vkBeautify#*                        resolve https://github.com/kayhadrin/vkBeautify.git#*
#0 1.434 bower angular-file-saver#^1.1.2        not-cached https://github.com/alferov/angular-file-saver.git#^1.1.2
#0 1.434 bower angular-file-saver#^1.1.2           resolve https://github.com/alferov/angular-file-saver.git#^1.1.2
#0 1.436 bower angular-animate#~1.5.10          not-cached https://github.com/angular/bower-angular-animate.git#~1.5.10
#0 1.436 bower angular-animate#~1.5.10             resolve https://github.com/angular/bower-angular-animate.git#~1.5.10
#0 1.437 bower angular-loading-bar#^0.9.0       not-cached https://github.com/chieffancypants/angular-loading-bar.git#^0.9.0
#0 1.437 bower angular-loading-bar#^0.9.0          resolve https://github.com/chieffancypants/angular-loading-bar.git#^0.9.0
#0 1.439 bower jquery#*                         not-cached https://github.com/jquery/jquery-dist.git#*
#0 1.439 bower jquery#*                            resolve https://github.com/jquery/jquery-dist.git#*
#0 1.440 bower angularjs-slider#^5.5.1          not-cached https://github.com/rzajac/angularjs-slider.git#^5.5.1
#0 1.441 bower angularjs-slider#^5.5.1             resolve https://github.com/rzajac/angularjs-slider.git#^5.5.1
#0 1.442 bower leaflet-measure#^2.1.7           not-cached https://github.com/ljagis/leaflet-measure.git#^2.1.7
#0 1.442 bower leaflet-measure#^2.1.7              resolve https://github.com/ljagis/leaflet-measure.git#^2.1.7
#0 1.443 bower angular-translate-loader-static-files#2.13.0       not-cached https://github.com/PascalPrecht/bower-angular-translate-loader-static-files.git#2.13.0
#0 1.444 bower angular-translate-loader-static-files#2.13.0          resolve https://github.com/PascalPrecht/bower-angular-translate-loader-static-files.git#2.13.0
#0 1.445 bower angular-ui-sortable#^0.14.3                        not-cached https://github.com/angular-ui/ui-sortable.git#^0.14.3
#0 1.445 bower angular-ui-sortable#^0.14.3                           resolve https://github.com/angular-ui/ui-sortable.git#^0.14.3
#0 1.472 bower leaflet.heightgraph#^0.1.6                         not-cached https://github.com/GIScience/Leaflet.Heightgraph.git#^0.1.6
#0 1.472 bower leaflet.heightgraph#^0.1.6                            resolve https://github.com/GIScience/Leaflet.Heightgraph.git#^0.1.6
#0 1.482 bower ngclipboard#^2.0.0                                 not-cached https://github.com/sachinchoolur/ngclipboard.git#^2.0.0
#0 1.482 bower ngclipboard#^2.0.0                                    resolve https://github.com/sachinchoolur/ngclipboard.git#^2.0.0
#0 1.483 bower semantic#^2.2.3                                    not-cached https://github.com/Semantic-Org/Semantic-UI.git#^2.2.3
#0 1.483 bower semantic#^2.2.3                                       resolve https://github.com/Semantic-Org/Semantic-UI.git#^2.2.3
#0 1.489 bower ng-focus-if#^1.0.7                                 not-cached https://github.com/hiebj/ng-focus-if.git#^1.0.7
#0 1.489 bower ng-focus-if#^1.0.7                                    resolve https://github.com/hiebj/ng-focus-if.git#^1.0.7
#0 1.658 bower leaflet.locatecontrol#^0.62.0                      not-cached https://github.com/domoritz/leaflet-locatecontrol.git#^0.62.0
#0 1.658 bower leaflet.locatecontrol#^0.62.0                         resolve https://github.com/domoritz/leaflet-locatecontrol.git#^0.62.0
#0 1.709 bower leaflet-distance-markers#*                           download https://github.com/adoroszlai/leaflet-distance-markers/archive/master.tar.gz
#0 1.901 bower font-awesome#^4.6.3                                  download https://github.com/FortAwesome/Font-Awesome/archive/v4.7.0.tar.gz
#0 1.912 bower leaflet.editable#^1.0.0                              download https://github.com/yohanboniface/Leaflet.Editable/archive/1.2.0.tar.gz
#0 2.472 bower angular-cookies#~1.5.10                              download https://github.com/angular/bower-angular-cookies/archive/v1.5.11.tar.gz
#0 2.496 bower leaflet.markercluster#^1.0.3                         download https://github.com/Leaflet/Leaflet.markercluster/archive/v1.5.3.tar.gz
#0 2.510 bower angular-tooltips#^1.1.8                              download https://github.com/720kb/angular-tooltips/archive/1.2.2.tar.gz
#0 2.525 bower d3-tip#v0.7.1                                        download https://github.com/Caged/d3-tip/archive/v0.7.1.tar.gz
#0 2.554 bower jquery-ui#^1.12.0                                    download https://github.com/components/jqueryui/archive/1.12.1.tar.gz
#0 2.706 bower angular-sanitize#1.5.9                               download https://github.com/angular/bower-angular-sanitize/archive/v1.5.9.tar.gz
#0 2.739 bower leaflet-distance-markers#*                            extract archive.tar.gz
#0 2.811 bower leaflet-distance-markers#*                           resolved https://github.com/adoroszlai/leaflet-distance-markers.git#258215e608
#0 2.999 bower angular-translate#2.13.0                             download https://github.com/PascalPrecht/bower-angular-translate/archive/2.13.0.tar.gz
#0 3.009 bower vkBeautify#*                                         download https://github.com/kayhadrin/vkBeautify/archive/master.tar.gz
#0 3.059 bower angular-file-saver#^1.1.2                            download https://github.com/alferov/angular-file-saver/archive/1.1.3.tar.gz
#0 3.078 bower rxjs#*                                               download https://github.com/Reactive-Extensions/RxJS/archive/v4.1.0.tar.gz
#0 3.642 bower angular-animate#~1.5.10                              download https://github.com/angular/bower-angular-animate/archive/v1.5.11.tar.gz
#0 3.701 bower angularjs-slider#^5.5.1                              download https://github.com/rzajac/angularjs-slider/archive/5.9.0.tar.gz
#0 3.714 bower jquery#*                                             download https://github.com/jquery/jquery-dist/archive/3.6.0.tar.gz
#0 3.722 bower angular-loading-bar#^0.9.0                           download https://github.com/chieffancypants/angular-loading-bar/archive/0.9.0.tar.gz
#0 3.732 bower leaflet-measure#^2.1.7                               download https://github.com/ljagis/leaflet-measure/archive/2.1.7.tar.gz
#0 3.750 bower angular-cookies#~1.5.10                               extract archive.tar.gz
#0 3.751 bower d3-tip#v0.7.1                                         extract archive.tar.gz
#0 3.764 bower angular-tooltips#^1.1.8                               extract archive.tar.gz
#0 3.770 bower leaflet.editable#^1.0.0                               extract archive.tar.gz
#0 3.887 bower font-awesome#^4.6.3                                   extract archive.tar.gz
#0 3.924 bower angular-translate-loader-static-files#2.13.0         download https://github.com/PascalPrecht/bower-angular-translate-loader-static-files/archive/2.13.0.tar.gz
#0 3.975 bower leaflet.markercluster#^1.0.3                          extract archive.tar.gz
#0 3.995 bower angular-cookies#~1.5.10                              resolved https://github.com/angular/bower-angular-cookies.git#1.5.11
#0 4.183 bower jquery-ui#^1.12.0                                     extract archive.tar.gz
#0 4.212 bower angular#1.5.11                                     not-cached https://github.com/angular/bower-angular.git#1.5.11
#0 4.212 bower angular#1.5.11                                        resolve https://github.com/angular/bower-angular.git#1.5.11
#0 4.217 bower d3-tip#v0.7.1                                        resolved https://github.com/Caged/d3-tip.git#0.7.1
#0 4.308 bower vkBeautify#*                                          extract archive.tar.gz
#0 4.329 bower ngclipboard#^2.0.0                                   download https://github.com/sachinchoolur/ngclipboard/archive/2.0.0.tar.gz
#0 4.352 bower angular-ui-sortable#^0.14.3                          download https://github.com/angular-ui/ui-sortable/archive/v0.14.4.tar.gz
#0 4.356 bower leaflet.heightgraph#^0.1.6                           download https://github.com/GIScience/Leaflet.Heightgraph/archive/0.1.6.tar.gz
#0 4.403 bower semantic#^2.2.3                                      download https://github.com/Semantic-Org/Semantic-UI/archive/2.4.1.tar.gz
#0 4.414 bower d3#^4.2                                            not-cached https://github.com/mbostock-bower/d3-bower.git#^4.2
#0 4.414 bower d3#^4.2                                               resolve https://github.com/mbostock-bower/d3-bower.git#^4.2
#0 4.438 bower angular-file-saver#^1.1.2                             extract archive.tar.gz
#0 4.472 bower ng-focus-if#^1.0.7                                   download https://github.com/hiebj/ng-focus-if/archive/v1.0.7.tar.gz
#0 4.530 bower angular-tooltips#^1.1.8                          invalid-meta for:/tmp/5b8a4476e26af4d1887dcdfb85034539/bower/867d7b279a77659668bc9bdc133e522e-1-Adf98n/bower.json
#0 4.530 bower angular-tooltips#^1.1.8                          invalid-meta The "main" field cannot contain minified files
#0 4.530 bower angular-tooltips#^1.1.8                          invalid-meta The "main" field cannot contain minified files
#0 4.650 bower angular-translate#2.13.0                              extract archive.tar.gz
#0 4.651 bower angular-loading-bar#^0.9.0                            extract archive.tar.gz
#0 4.743 bower angular-animate#~1.5.10                               extract archive.tar.gz
#0 4.747 bower angular-tooltips#^1.1.8                              resolved https://github.com/720kb/angular-tooltips.git#1.2.2
#0 4.767 bower vkBeautify#*                                     invalid-meta for:/tmp/5b8a4476e26af4d1887dcdfb85034539/bower/b22ff4ddd62c9bb4eb365e50c4dc7354-1-0vDgfo/bower.json
#0 4.767 bower vkBeautify#*                                     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
#0 4.809 bower vkBeautify#*                                         resolved https://github.com/kayhadrin/vkBeautify.git#a08344e94d
#0 4.832 bower angular-translate#2.13.0                             resolved https://github.com/PascalPrecht/bower-angular-translate.git#2.13.0
#0 4.936 bower angular-animate#~1.5.10                              resolved https://github.com/angular/bower-angular-animate.git#1.5.11
#0 4.949 bower leaflet.editable#^1.0.0                              mismatch Version declared in the json (0.6.0) is different than the resolved one (1.2.0)
#0 4.962 bower leaflet.editable#^1.0.0                              resolved https://github.com/yohanboniface/Leaflet.Editable.git#1.2.0
#0 5.002 bower leaflet.locatecontrol#^0.62.0                        download https://github.com/domoritz/leaflet-locatecontrol/archive/v0.62.0.tar.gz
#0 5.044 bower jquery#*                                              extract archive.tar.gz
#0 5.102 bower leaflet-measure#^2.1.7                                extract archive.tar.gz
#0 5.186 bower angular-sanitize#1.5.9                                extract archive.tar.gz
#0 5.196 bower angular-loading-bar#^0.9.0                           resolved https://github.com/chieffancypants/angular-loading-bar.git#0.9.0
#0 5.241 bower angular-translate-loader-static-files#2.13.0          extract archive.tar.gz
#0 5.290 bower angular-sanitize#1.5.9                               resolved https://github.com/angular/bower-angular-sanitize.git#1.5.9
#0 5.292 bower angular#1.5.9                                      not-cached https://github.com/angular/bower-angular.git#1.5.9
#0 5.292 bower angular#1.5.9                                         resolve https://github.com/angular/bower-angular.git#1.5.9
#0 5.307 bower angular-ui-sortable#^0.14.3                           extract archive.tar.gz
#0 5.326 bower angular-translate-loader-static-files#2.13.0         resolved https://github.com/PascalPrecht/bower-angular-translate-loader-static-files.git#2.13.0
#0 5.356 bower angular-file-saver#^1.1.2                            resolved https://github.com/alferov/angular-file-saver.git#1.1.3
#0 5.358 bower ngclipboard#^2.0.0                                    extract archive.tar.gz
#0 5.369 bower rxjs#*                                                extract archive.tar.gz
#0 5.379 bower angularjs-slider#^5.5.1                               extract archive.tar.gz
#0 5.401 bower angular-ui-sortable#^0.14.3                          resolved https://github.com/angular-ui/ui-sortable.git#0.14.4
#0 5.404 bower jquery#<3.0.0                                      not-cached https://github.com/jquery/jquery-dist.git#<3.0.0
#0 5.404 bower jquery#<3.0.0                                         resolve https://github.com/jquery/jquery-dist.git#<3.0.0
#0 5.415 bower jquery#<3.0.0                                        download https://github.com/jquery/jquery-dist/archive/2.2.4.tar.gz
#0 5.439 bower ng-focus-if#^1.0.7                                    extract archive.tar.gz
#0 5.449 bower leaflet.heightgraph#^0.1.6                            extract archive.tar.gz
#0 5.490 bower file-saver.js#~1.20150507.2                        not-cached https://github.com/Teleborder/FileSaver.js.git#~1.20150507.2
#0 5.490 bower file-saver.js#~1.20150507.2                           resolve https://github.com/Teleborder/FileSaver.js.git#~1.20150507.2
#0 5.526 bower jquery-ui#>=1.9                                    not-cached https://github.com/components/jqueryui.git#>=1.9
#0 5.526 bower jquery-ui#>=1.9                                       resolve https://github.com/components/jqueryui.git#>=1.9
#0 5.527 bower blob-polyfill#~1.0.20150320                        not-cached https://github.com/bjornstar/blob-polyfill.git#~1.0.20150320
#0 5.527 bower blob-polyfill#~1.0.20150320                           resolve https://github.com/bjornstar/blob-polyfill.git#~1.0.20150320
#0 5.532 bower jquery-ui#>=1.9                                      download https://github.com/components/jqueryui/archive/1.12.1.tar.gz
#0 5.620 bower leaflet.markercluster#^1.0.3                     invalid-meta for:/tmp/5b8a4476e26af4d1887dcdfb85034539/bower/d17d2a62edd373f768b64591f84f6d5d-1-sRIH27/bower.json
#0 5.620 bower leaflet.markercluster#^1.0.3                     invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .css files: ["dist/MarkerCluster.css","dist/MarkerCluster.Default.css"]
#0 5.690 bower ng-focus-if#^1.0.7                                   resolved https://github.com/hiebj/ng-focus-if.git#1.0.7
#0 5.722 bower leaflet.heightgraph#^0.1.6                       invalid-meta for:/tmp/5b8a4476e26af4d1887dcdfb85034539/bower/46115f5d68e8e0053e030109cc37e87e-1-Rv4oCk/bower.json
#0 5.722 bower leaflet.heightgraph#^0.1.6                       invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
#0 5.760 bower ngclipboard#^2.0.0                                   resolved https://github.com/sachinchoolur/ngclipboard.git#2.0.0
#0 5.808 bower leaflet.markercluster#^1.0.3                         mismatch Version declared in the json (1.4.1) is different than the resolved one (1.5.3)
#0 5.818 bower leaflet.markercluster#^1.0.3                         resolved https://github.com/Leaflet/Leaflet.markercluster.git#1.5.3
#0 5.837 bower leaflet.heightgraph#^0.1.6                           mismatch Version declared in the json (0.1.2) is different than the resolved one (0.1.6)
#0 5.847 bower leaflet.heightgraph#^0.1.6                           resolved https://github.com/GIScience/Leaflet.Heightgraph.git#0.1.6
#0 5.869 bower leaflet-measure#^2.1.7                           invalid-meta for:/tmp/5b8a4476e26af4d1887dcdfb85034539/bower/451e56e44ed2f894049770854e68af68-1-QicyPJ/bower.json
#0 5.869 bower leaflet-measure#^2.1.7                           invalid-meta The "main" field cannot contain minified files
#0 5.942 bower clipboard#^2.0.0                                   not-cached https://github.com/zenorocha/clipboard.js.git#^2.0.0
#0 5.942 bower clipboard#^2.0.0                                      resolve https://github.com/zenorocha/clipboard.js.git#^2.0.0
#0 6.005 bower leaflet-measure#^2.1.7                               resolved https://github.com/ljagis/leaflet-measure.git#2.1.7
#0 6.053 bower leaflet#1.0.3                                      not-cached https://github.com/Leaflet/Leaflet.git#1.0.3
#0 6.053 bower leaflet#1.0.3                                         resolve https://github.com/Leaflet/Leaflet.git#1.0.3
#0 6.068 bower leaflet#>= 1.3.1                                   not-cached https://github.com/Leaflet/Leaflet.git#>= 1.3.1
#0 6.068 bower leaflet#>= 1.3.1                                      resolve https://github.com/Leaflet/Leaflet.git#>= 1.3.1
#0 6.075 bower leaflet.locatecontrol#^0.62.0                         extract archive.tar.gz
#0 6.140 bower d3#^4.2                                              download https://github.com/mbostock-bower/d3-bower/archive/v4.13.0.tar.gz
#0 6.231 bower angularjs-slider#^5.5.1                              resolved https://github.com/rzajac/angularjs-slider.git#5.9.0
#0 6.275 bower jquery#<3.0.0                                         extract archive.tar.gz
#0 6.309 bower blob-polyfill#~1.0.20150320                          download https://github.com/bjornstar/blob-polyfill/archive/1.0.20150320.tar.gz
#0 6.403 bower leaflet.locatecontrol#^0.62.0                        resolved https://github.com/domoritz/leaflet-locatecontrol.git#0.62.0
#0 6.435 bower clipboard#^2.0.0                                     download https://github.com/zenorocha/clipboard.js/archive/v2.0.11.tar.gz
#0 6.653 bower angular#1.5.9                                        download https://github.com/angular/bower-angular/archive/v1.5.9.tar.gz
#0 6.653 bower angular#1.5.11                                       download https://github.com/angular/bower-angular/archive/v1.5.11.tar.gz
#0 6.662 bower leaflet#>= 1.3.1                                     download https://github.com/Leaflet/Leaflet/archive/v1.8.0.tar.gz
#0 6.662 bower leaflet#1.0.3                                        download https://github.com/Leaflet/Leaflet/archive/v1.0.3.tar.gz
#0 6.688 bower semantic#^2.2.3                                       extract archive.tar.gz
#0 6.719 bower jquery-ui#>=1.9                                       extract archive.tar.gz
#0 6.876 bower jquery#*                                             resolved https://github.com/jquery/jquery-dist.git#3.6.0
#0 7.047 bower blob-polyfill#~1.0.20150320                           extract archive.tar.gz
#0 7.095 bower d3#^4.2                                               extract archive.tar.gz
#0 7.121 bower blob-polyfill#~1.0.20150320                          resolved https://github.com/bjornstar/blob-polyfill.git#1.0.20150320
#0 7.183 bower d3#^4.2                                              resolved https://github.com/mbostock-bower/d3-bower.git#4.13.0
#0 7.312 bower clipboard#^2.0.0                                      extract archive.tar.gz
#0 7.383 bower jquery#<3.0.0                                        resolved https://github.com/jquery/jquery-dist.git#2.2.4
#0 7.706 bower clipboard#^2.0.0                                     resolved https://github.com/zenorocha/clipboard.js.git#2.0.11
#0 7.864 bower angular#1.5.11                                        extract archive.tar.gz
#0 7.991 bower angular#1.5.11                                       resolved https://github.com/angular/bower-angular.git#1.5.11
#0 8.388 bower angular#1.5.9                                         extract archive.tar.gz
#0 8.401 bower jquery-ui#^1.12.0                                    resolved https://github.com/components/jqueryui.git#1.12.1
#0 8.499 bower angular#1.5.9                                        resolved https://github.com/angular/bower-angular.git#1.5.9
#0 9.130 bower jquery-ui#>=1.9                                      resolved https://github.com/components/jqueryui.git#1.12.1
#0 9.592 bower font-awesome#^4.6.3                                  resolved https://github.com/FortAwesome/Font-Awesome.git#4.7.0
#0 10.29 bower leaflet#1.0.3                                         extract archive.tar.gz
#0 10.34 bower semantic#^2.2.3                                      resolved https://github.com/Semantic-Org/Semantic-UI.git#2.4.1
#0 10.44 bower leaflet#>= 1.3.1                                      extract archive.tar.gz
#0 11.36 bower leaflet#1.0.3                                        resolved https://github.com/Leaflet/Leaflet.git#1.0.3
#0 11.71 bower rxjs#*                                               resolved https://github.com/Reactive-Extensions/RxJS.git#4.1.0
#0 11.96 bower leaflet#>= 1.3.1                                     resolved https://github.com/Leaflet/Leaflet.git#1.8.0
#0 11.96 bower file-saver.js#~1.20150507.2                           ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/Teleborder/FileSaver.js.git", exit code of #128 remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead. remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information. fatal: Authentication failed for 'https://github.com/Teleborder/FileSaver.js.git/'
#0 11.96
#0 11.96 Additional error details:
#0 11.96 remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
#0 11.96 remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
#0 11.96 fatal: Authentication failed for 'https://github.com/Teleborder/FileSaver.js.git/'
------
>failed to solve: executor failed running [/bin/sh -c node_modules/bower/bin/bower install --allow-root]: exit code: 1`

**Comment by TheGreatRefrigerator** [comment]
Hi @st3inar,

https://stackoverflow.com/questions/71979265/unable-to-resolve-file-saver-js-dependency-file-from-bower-install-angular-file
try moving the  `"angular-file-saver": "^1.1.2"` from the `bower.json` file to the `package.json` dependency, so it will be installed via npm. You will still need to change the imports afterwards. Just search for angular-file-saver in the repository and you will see where you need to change to the location of the package in the `node-module` folder.

Afterwards do a `docker-compose build --no-cache` and you should be good to go.
If you want you can do a PR with the changes.

Best regards
