### ISSUE TITLE
Consider traffic information in route computation

### ISSUE THREAD

**Issue by TimMcCauley** [GIScience/openrouteservice-app#4]
_From @TimMcCauley on December 13, 2015 10:18_

The new ORS backend allows specifying whether traffic information is considered in route computation or not. This can be done by providing useRealTimeTraffic attribute for xls:RoutePlan element.
<?xml version="1.0" encoding="UTF-8" ?>
<xls:XLS xmlns:xls="http://www.opengis.net/xls" xsi:schemaLocation="http://www.opengis.net/xls http://schemas.opengis.net/ols/1.1.0/RouteService.xsd" xmlns:sch="http://www.ascc.net/xml/schematron" xmlns:gml="http://www.opengis.net/gml" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.1" xls:lang="en">
    xls:RequestHeader
    /xls:RequestHeader
    <xls:Request methodName="RouteRequest" version="1.1" requestID="00" maximumResponses="15">
        xls:DetermineRouteRequest
            <xls:RoutePlan  useRealTimeTraffic="true">
                xls:RoutePreferenceCar/xls:RoutePreference
                xls:ExtendedRoutePreference
                    xls:WeightingMethodFastest/xls:WeightingMethod
                /xls:ExtendedRoutePreference
                xls:WayPointList
                    xls:StartPoint
                        xls:Position
                            <gml:Point xmlns:gml="http://www.opengis.net/gml">
                                <gml:pos srsName="EPSG:4326">8.20440472118994 49.36902403998967/gml:pos
                            /gml:Point
                        /xls:Position
                    /xls:StartPoint
                    xls:EndPoint
                        xls:Position
                            <gml:Point xmlns:gml="http://www.opengis.net/gml">
                                <gml:pos srsName="EPSG:4326">8.18045795910493 49.32350720550303/gml:pos
                            /gml:Point
                        /xls:Position
                    /xls:EndPoint
                /xls:WayPointList
                <xls:AvoidList />
            /xls:RoutePlan
            <xls:RouteInstructionsRequest provideGeometry="true" />
            xls:RouteGeometryRequest
            /xls:RouteGeometryRequest
        /xls:DetermineRouteRequest
    /xls:Request
/xls:XLS

This new feature useRealTraffic requires an additional UI element (see figure below), which will allow user to enable or disable this feature. Note, this feature must be visible only for car related profiles. Furthermore, as it can be seen from the figure, the ui is becoming a bit messy. Therefore, we need to think about rearranging/grouping the following elements: maximum speed, consider traffic (Germany only), avoid features.

_Copied from original issue: GIScience/openrouteservice#234_

**Comment by garro95** [comment]
Some traffic information for the city of Turin (Italy) are available as opendata from http://opendata.5t.torino.it/get_fdt
The same agency (5t) also provides information about parking areas and controlled traffic zones if you are interested to add some features that need these data for the route planning
