### ISSUE TITLE
downloaded gpx files containing only the waypoints - the detailed track is missing

### ISSUE THREAD

**Issue by dw-loewe** [GIScience/openrouteservice-app#65]
on my smartphone i'm using osmand~ and until now, i tried so often with each formats i am able to download on OSR to import those in the routing app.. But it does not work any more as before: in osmand~ only the single waypoints apper (a lot of informations sometimes let crash my Galaxy S2) – but not the whole route as track! But that's i really need – others than the gpx format aren't accepted in osmand~. Before the upgrade of the api of OSR)the import of files from OSR to osmand~ with the same version of osmand~ did work fine! So i only can explain that behavior to me with the supposition, that these files exportet from OSR are lacking of track-information. Before the upgrade, i could choose to download different file GPX-file-types: with and without waypoints. please reintegrate that! :)

**Comment by TimMcCauley** [comment]
Thanks for the report, this will be fixed next week. I am already working on it.

**Comment by TimMcCauley** [comment]
Please clear your cache, this bug should now be fixed.
