### ISSUE TITLE
Elevation data

### ISSUE THREAD

**Issue by dalkvist** [GIScience/openrouteservice-app#72]
Any plans to in cooperate more elevation data sources?
It look like you only have the SRTM from the way it [cuts of at 60N](https://openrouteservice.org/directions?a=60.138251,12.998881,59.840181,13.135481&b=1a&c=0&g1=-1&g2=0&h2=3&k1=en&k2=km). 
There are dem data available for Sweden under ccby4, see  [dataset "GSD-Höjddata, grid 50+"](http://www.lantmateriet.se/en/Maps-and-geographic-information/Maps/oppna-data/hamta-oppna-geodata/)

**Comment by TimMcCauley** [comment]
Thank you for the report, we will check this out!

**Comment by Sandmania** [comment]
Topographical data (from which I think you can generate the elevation information?) for Finland is also available as open data. See [Topographic data and how to acquire it](http://www.maanmittauslaitos.fi/en/maps-and-spatial-data/expert-users/topographic-data-and-how-acquire-it) from the National Land Survey of Finland, if you are interested.

Edit: Seems like there is a [separate information page for the elevation data](http://www.maanmittauslaitos.fi/en/maps-and-spatial-data/expert-users/product-descriptions/elevation-model-10-m)

**Comment by TimMcCauley** [comment]
We are closing this feature as we currently don't have the resources to fulfill it.
