### ISSUE TITLE
Points of interest widget

### ISSUE THREAD

**Issue by TimMcCauley** [GIScience/openrouteservice-app#75]
Features:
- Ability to click on location and query locations API again
- Ability to use location as waypoint along route
- Show locations along route
- Show locations in polygons

Done:

~~Show locations in bounding box~~
~~Add clustering~~

**Comment by TheGreatRefrigerator** [comment]
done with https://github.com/GIScience/openpoiservice/

**Comment by TimMcCauley** [comment]
Not everything of this is implemented yet, may happen in the future, reopening

**Comment by TimMcCauley** [comment]
@TheGreatRefrigerator how about we add the feature enabling users to query locations around a route with a given buffer?
