### ISSUE TITLE
Feature request: Allow user to control zoom levels in which certain map features are visible

### ISSUE THREAD

**Issue by Sandmania** [GIScience/openrouteservice-app#76]
OpenRouteService is an excellent tool when planning a hike and its route. Along popular hiking routes, there are usual some services like wells, open wilderness huts, lean-tos etc. Planning your route and legs/stages would be even easier, if those services/map features would be visible on a higher zoom level, say zoom 9.
Basically, just allow the user to override the default visible zoom level of (a limited amount of) features.

Is something like this technically possible and if so, is it a feature that you would consider adding to OpenRouteService?

**Comment by TimMcCauley** [comment]
Greetings Sandmania, we are actually adding this feature within the next 2 months. You will be able to query our locations API with categories of specific POIs and show them on the map. Here is the corresponding issue https://github.com/GIScience/openrouteservice-ng/issues/75 . I will close this comment. Please stay tuned for the next update, probably around end of june.
