### ISSUE TITLE
more routing preference settings please "Motorbike support"

### ISSUE THREAD

**Issue by DrDuc** [GIScience/openrouteservice-app#86]
hi, I am a passionate motor-biker and using OSM maps on Garmin since ages....
Route planning is always "challenging" since most routing engines do not support "Motorbike preferences" like:
- avoid Motorways and main roads
- prefer winding roads (typically not main roads)
- prefer scenic roads
- avoid directly going through cities (shortest way)
Typical "fast way" prefer motorways and main roads and "short way" go through lots of towns. And heavy rework with manual way point setting is necessary. 
Is there any way I can support specifying or implementing this?
BR, DrDuc

**Comment by TimMcCauley** [comment]
Greetings, thanks for the suggestion. We will discuss this!

**Comment by TimMcCauley** [comment]
Moved to backend issue.
